### ISSUE TITLE
Priority of the snippets

### ISSUE THREAD

**Issue by crazymaster** [Shougo/neosnippet.vim#150]
本体と他のスニペットで同じ候補があった場合、
どちらを補完候補として出すか選択できるようにしてほしい。

現状では同じ候補がある場合、他のスニペットだけが補完されるようです。

**Comment by Shougo** [comment]
現在は neosnippet のスニペットは分離されているので、neosnippet のスニペットで他のものを上書きすることは十分可能です。
クローズします。

**Comment by crazymaster** [comment]
すっかり忘れてた...
ありがとうございました :smile:
