### ISSUE TITLE
jump back

### ISSUE THREAD

**Issue by kdurant** [Shougo/neosnippet.vim#152]
neosnippet was perfect. Only one disadvantage is that the code snippet is not backward jump
Why do not you consider adding this feature?

**Comment by mvaisanen** [comment]
+1

**Comment by kusayuzayushko** [comment]
+1

**Comment by Nadrieril** [comment]
+1

**Comment by tomhedley** [comment]
+1

**Comment by Shougo** [comment]
It should be implemented in another snippet plugin.

https://github.com/Shougo/deoppet.nvim

**Comment by Shougo** [comment]
I don't add the feature in neosnippet.
It should be added in deoppet.nvim.
