### ISSUE TITLE
Understand expand target

### ISSUE THREAD

**Issue by rickywu** [Shougo/neosnippet.vim#155]
I can't understand target very well from help.

If there is ${2:TARGET}, after move the cursor to TARGET, then switch to visual mode, it ask me input trigger, but always got invalid trigger other than import for go language.
But input import will expand a duplicate import structure.

Could you give me more details about how to use it?

Thanks.

**Comment by gilfuser** [comment]
I have the same problem. I know this is not an issue, and I'm sorry for asking this here.
I don't know what `<Plug>(neosnippet_expand_target)` should be.

Thank you in advance for any direction given.

bests,
Gil

**Comment by Shougo** [comment]
> In TARGET placeholder, your selected text is expanded.
> It is useful for copying a text in block.

**Comment by gilfuser** [comment]
My question is: what should I press?

**Comment by Shougo** [comment]
https://github.com/Shougo/neosnippet.vim/issues/155#issuecomment-37529292

**Comment by Shougo** [comment]
You must map `<Plug>(neosnippet_expand_target)` before that.

**Comment by gilfuser** [comment]
Hi Shougo.
Thank you for taking the time to guide me on this.
I think we are getting there.
So, the remaining question is:
how do I do this mapping?

**Comment by Shougo** [comment]
Have you looked the documentation?

```
EXAMPLES					*neosnippet-examples*
>
	" Plugin key-mappings.
	" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
	imap <C-k>     <Plug>(neosnippet_expand_or_jump)
	smap <C-k>     <Plug>(neosnippet_expand_or_jump)
	xmap <C-k>     <Plug>(neosnippet_expand_target)
```

**Comment by lucainnocenti** [comment]
same problem here. I installed the default neosnippet snippets from the repository, but using `ctrl-k` in insert mode doesn't do anything. Is there a way to check which snippet files have been loaded?

**Comment by Shougo** [comment]
You must select text to expand target.
You should know what is xmap.

**Comment by lucainnocenti** [comment]
I get that, but I thought the snippets should also work in insert mode? Maybe I should just open a separate issue, but when I am in insert mode doing `<C-k>` does nothing (whereas when I have text selected I do get the "Please input snippet trigger" message)

**Comment by Shougo** [comment]
`<Plug>(neosnippet_expand_target)` does not work in insert mode.
 
To expand insert mode by `<Plug>(neosnippet_expand_or_jump)`, you need to select or input snippet trigger.
You should learn how to use neosnippet.
