### ISSUE TITLE
Shows the options in neosnippets but does not work with tab

### ISSUE THREAD

**Issue by vysakh0** [Shougo/neosnippet.vim#171]
![tmuxinator 1 0 editor_023](https://f.cloud.github.com/assets/1475197/836756/d5861204-f2f7-11e2-8b7e-cf49f93792c5.png)

It shows in neocomplete, but on pressing tab it does not expand the tab. When I do `source ~/.vimrc` the neosnippet completion works. 

I have used the same configuration as it is in the readme. I also load vim-snippets. Please help.

**Comment by EdmundsEcho** [comment]
2018 update: when I use
```
" SuperTab like snippets behavior.
    imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
     \ "\<Plug>(neosnippet_expand_or_jump)"
     \: pumvisible() ? "\<C-n>" : "\<TAB>"
    smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
     \ "\<Plug>(neosnippet_expand_or_jump)"
     \: "\<TAB>"
```
the `<Plug>` function does not get called; instead the string `"<Plug>(neosnippet...)"` is inserted.  When I do get the function to work, it expands as soon as the first neosnippet is selected in the suggestion menu.  This prevents selecting neosnippets that are not first on the list...

Suggestion: There might be value in either updating the post with the latest best practice, or if what I experience is more generally observed, then deprecating the post entry.

**Comment by Shougo** [comment]
@EdmundsEcho I think neosnippet plugin is not loaded.
You should check the mappings are defined.

**Comment by Shougo** [comment]
If it is neosnippet plugin problem, please create the minimal vimrc.
