### ISSUE TITLE
Please rename the snippet name or use `delete v`.

### ISSUE THREAD

**Issue by Netherdrake** [Shougo/neosnippet.vim#186]
I'm getting this error whenever I try to edit Golang file (ft=go).
`Please rename the snippet name or use delete v.`

I've got omni-complete to work by applying solution from here.
https://github.com/Shougo/neocomplete.vim/issues/29

Here is my .vimrc:
https://bitbucket.org/furion/dotfiles

Any ideas how to fix it?

**Comment by jwnweb** [comment]
this helped me with a similar error. Thanks, Shougo!
