### ISSUE TITLE
Add support for "File Snippets"

### ISSUE THREAD

**Issue by jsit** [Shougo/neosnippet.vim#196]
snipMate had support for "File Snippets", where the snippet trigger was in the filename, rather than in the contents of the file:

https://github.com/msanders/snipmate.vim/blob/562d78749d8463017e6773474d7fb3a543209e74/doc/snipMate.txt#L119

Several snippet packages still use this method, including spf13/snipmate-snippets and mklabs/snipmate-css3-please

Is it possible for neosnippet to support this snippet style?

**Comment by Shougo** [comment]
Implemented.

Note:  You must enable snipMate compatibility feature.
