### ISSUE TITLE
Reload snippets?

### ISSUE THREAD

**Issue by CRTX** [Shougo/neosnippet.vim#201]
When I'm in the middle of writing code and I want to add a new snippet I edit the snippets but they don't work until I reload vim. Is there already a command that reloads/updates the snippet so that they can be used after editing the snippet files?

**Comment by jaredmcateer** [comment]
Came across this problem. I was editing the snippets in another instance of vim so of course they didn't get reloaded. I prefer to do it that way so I mapped a key to this:

`nnoremap <leader>rs :call neosnippet#variables#set_snippets({})<cr>`

**Comment by Shougo** [comment]
@jaredmcateer `:NeoSnippetMakeCache`
