### ISSUE TITLE
Installation via pathogen.

### ISSUE THREAD

**Issue by itissid** [Shougo/neosnippet.vim#222]
Is there a reason to believe that this wont install with pathogen?

**Comment by jerryling315** [comment]
@Shougo I'm not sure what are you talking about there. What do you mean by, Pathogen connot install any plugins?

**Comment by Shougo** [comment]
Yes.
It just load plugins from you specified directory.

**Comment by jerryling315** [comment]
What else dose Vundle do? Compilation?

**Comment by Shougo** [comment]
Vundle can install plugins.

**Comment by jerryling315** [comment]
I don't know if NerdTree counts as a plugin or not. But it works under pathogen.
