### ISSUE TITLE
neosnippet slow in large LaTeX document

### ISSUE THREAD

**Issue by Konfekt** [Shougo/neosnippet.vim#234]
neosnippet becomes slower and slower under Gvim 7.4.282 in Windows 7 64 bit, when the LaTeX document becomes larger and larger.

This is independent of the conceallevel.

Is this to be expected?

**Comment by antenore** [comment]
:+1: Old thread but still very useful, thanks!

**Comment by Konfekt** [comment]
In the meanwhile try https://github.com/Konfekt/FastFold if you use folds.

**Comment by Shougo** [comment]
@Konfekt Oh, it is the good information!

**Comment by Konfekt** [comment]
Happy to hear that and being able to recontribute with a minor plugin.
