### ISSUE TITLE
format the mirror text

### ISSUE THREAD

**Issue by zhyzky** [Shougo/neosnippet.vim#246]
This is the same feature request as this:
http://stackoverflow.com/questions/5064430/changing-the-case-within-snipmate-vim-snippets
For example:

```
snippet dc
  def create
    @${1} = $1.new
  end
```

Should output:

```
def create
  @product = Product.new
end
```

There is a sollution in the webpage, but I don't know where to put the code from the 2nd answer. Appreciate if you can help.

**Comment by Shougo** [comment]
This feature may be supported by #269.

**Comment by Shougo** [comment]
Closing.
