### ISSUE TITLE
Issue with optional placeholder

### ISSUE THREAD

**Issue by ianks** [Shougo/neosnippet.vim#263]
When given this snippet, the optional place holder text is interpolated incorrectly:

```
snippet frontmatter
abbr frontmatter for Jekyll
options head
  ---
  title: ${1:#:title}
  date:  `strftime("%Y-%m-%d")`
  tags:  ${2:#:tags}
  ---

  ${0}
```

It renders this:

```
---
title: title
date: 2015-01-07
tags:  #:tags
---

```

This error goes away when you remove the `---` on the bottom however. I tried escaping the those characters to no avail (I could be doing it wrong...). Other than the text looking odd, everything works perfectly as expected so it's a relatively trivial issue. Just thought I would give a heads up!

**Comment by Shougo** [comment]
OK.  I will check it.

**Comment by Shougo** [comment]
I get it.  It is indent plugin indentation.
You must use tab characters instead of spaces.
