### ISSUE TITLE
NeoSnippit cache error

### ISSUE THREAD

**Issue by chasingtheflow** [Shougo/neosnippet.vim#264]
Whenever I first attempt to make an edit in a file a receive the following error:

![neosnippet error](https://cloud.githubusercontent.com/assets/718368/5682634/71d89616-97ef-11e4-821a-a50822e78f85.png)

I feel like I must have some sort of file permissions problem, but I'm not sure how to fix ... my .cache/ folder permissions look like:

drwxrwxr-x   4 root   staff    136 Jan  7 18:51 .cache/

**Comment by Shougo** [comment]
```
drwxrwxr-x 4 root staff 136 Jan 7 18:51 .cache/
```

It is permission error.  I think you created the directory by `sudo vim`. You must remove .cache directory.
