### ISSUE TITLE
Question: integrity of the plugin.

### ISSUE THREAD

**Issue by llfm** [Shougo/neosnippet.vim#266]
My settings:
```vim
set conceallevel=2
set concealcursor=i

let g:neosnippet#disable_runtime_snippets = {'_': 1}
let g:neosnippet#enable_snipmate_compatibility = 1
let g:neosnippet#snippets_directory='~/.vim/plugged/vim-snippets/snippets'
```
1) I can't use Ultisnips folder. Changing the snippets_directory to Ultisnips doesn't load any snippet.
2) The markers are SOMETIMES displayed.
e.g.
Using snipmate snippets, with this in _.snippets:
```snippet
snippet ctt
    /*!
        ${1:file}
        ${2:comment}
    */
```
Open a `cpp` file and type `ctt` and expand it. Two problems here: 
- Doesn't respect the indentation of the second placeholder (I'm using spaces)
- When you expand it, the conceal feature works.
- Now, try to expand the `array` snippet. It will show the markers: ```std::array<T, <`2:N`>> <`3`>;```.

3) The ultisnips plugin automatically loads the c and cpp snippets for a cpp file. This is possible in neosnippet?
4) In order to avoid some lag in each snippet, do I really need to make a manual cache of each filetype I opened?

I can make a minimal .vimrc for some of the question if needed.
Thanks

**Comment by ujihisa** [comment]
> indentation

```vim
:h neosnippet
```

```help
If you use hard-tab for indentation inside a snippet file, neosnippet will use
'shiftwidth' instead of Vim indent plugin. This feature is useful while some
languages' indent files do not work very well (e.g.: PHP, Python).
>
	snippet if
	  if (${1:/* condition */}) {
	      ${2:// code...}
	  }
<
```

**Comment by llfm** [comment]
> indentation

`If you use hard-tab for indentation`
I don't, I'm using spaces. But anyway, I tested with hard tabs and I get the same thing.
Using this snippet (with space/tab indentation):
```snippet
snippet ctt
    /*!
        ${1:file}
        ${2:comment}
    */
```
Code expected:
```snippet
/*!
    ${1:file}
    ${2:comment}
*/
```
Code resulted:
```snippet
/*!
    ${1:file}
    ${2:comment}
    */
```

**Comment by Shougo** [comment]
Please upload full of minimal .vimrc.   You .vimrc is splitted.
I will check it.

**Comment by Shougo** [comment]
I tested. 

If the spaces are whitespaces, the problem is reproduced.  But it is feature.
If the spaces are hard tabs, the problem is not reproduced.

I think it is not neosnippet bug.  But it may be the plugin or the configuration conflict.

**Comment by Shougo** [comment]
> The ultisnips plugin automatically loads the c and cpp snippets for a cpp file. This is possible in neosnippet?

You can use include feature in snippet file.

> In order to avoid some lag in each snippet, do I really need to make a manual cache of each filetype I opened?

`NeoSnippetMakeCache`

> Now, try to expand the array snippet. It will show the markers: `std::array<T, <`2:N`>> <`3`>;`

I cannot get the array snippet.  Please upload it and minimal .vimrc.

> I can't use Ultisnips folder. Changing the snippets_directory to Ultisnips doesn't load any snippet.

It is feature.  neosnippet cannot load UltiSnips snippets.

**Comment by llfm** [comment]
Thanks for the reply Shougo!

> indentation

I tested the hard tabs poorly before. Now it works. Perhaps it would be nice to make it more clear in the docs.

> include

This feature is only available in neosnippets. No way of doing this using snipmate snippets?

> cache

Yes, I said `do I really need to make a manual cache of each filetype I open`, in another words: do I really need to run this command to every new filetype I open?

> ultisnips

That's ok.

minimal.vimrc:
```vim
set nocompatible
set conceallevel=2
set concealcursor=i

call plug#begin('~/.vim/plugged')
    Plug 'Shougo/neosnippet.vim'
call plug#end()

let g:neosnippet#disable_runtime_snippets = {'_': 1}
let g:neosnippet#enable_snipmate_compatibility = 1
let g:neosnippet#snippets_directory='~/.vim/plugged/vim-snippets/snippets'

imap <C-k> <Plug>(neosnippet_expand_or_jump)
```

-> vim -u minimal.vimrc tt.cc
-> type cl + `ctrl+k`       = error messages
-> type array + `ctrl+k` = `std::array<T, <'2:N'>> <'3'>`
-> vim -u minimal.vimrc tt.rb
-> type case + `ctrl+k`  = normal snippet

I could change to neosnippets. But the repo of honza is more complete and updated.
Thank you.

**Comment by Shougo** [comment]
> I tested the hard tabs poorly before. Now it works. Perhaps it would be nice make it more clear in the docs.

Pull request is wellcome.

> This feature is only available in neosnippets. No way of doing this using snipmate snippets?

`:help g:neosnippet#scope_aliases`

> Yes, I said do I really need to make a manual cache of each filetype I open, in another words: do I really need to run this command to every new filetype I open?

`autocmd FileType * NeoSnippetMakeCache`

**Comment by Shougo** [comment]
> type cl + ctrl+k = error messages

To use honza snippets, you must add runtimepath to honza function.

```vim
set runtimepath+=~/.vim/plugged/vim-snippets
```

> `type array + ctrl+k = std::array<T, <'2:N'>> <'3'> `

OK.  I get it.  You must set concealcursor like below.

```vim
set concealcursor=niv
```
