### ISSUE TITLE
What does the snipit complete marker do?

### ISSUE THREAD

**Issue by mmynsted** [Shougo/neosnippet.vim#267]
I see the following in the configuration example
```VimL
" For snippet_complete marker.
if has('conceal')
  set conceallevel=2 concealcursor=i
endif
```     

This causes behavior that I did not expect when trying to add the following to scala code.
```scala
<|*|>
```

What is the intention of the `snippet_complete marker` and is it necessary?

**Comment by Shougo** [comment]
It is necessary.  It is used for find the jump positions easily in neosnippet implementation.
I think it is neosnippet feature.
If you don't want to use the markers, you should use other snippet plugins like snipMate or UltiSnips.

**Comment by mmynsted** [comment]
So if I disable it to make `<|*|>` then I will break `neosnippet`?

**Comment by Shougo** [comment]
You should set `concealcursor=inv`.  I changed the documentation.

**Comment by wsdjeg** [comment]
i have add set concealcursor=inv. set canceallevel = 2 into my vimrc,but when i open a file 
this command also show
set concealcursor?
show concealcursor=inc
set comceallevel?
show conceallevel=2

**Comment by Shougo** [comment]
@wsdjeg Hint: `:verbose set concealcursor?`

**Comment by wsdjeg** [comment]
thanks ,it is due to indentLine.vim it is a after plugin
