### ISSUE TITLE
Snippet editing

### ISSUE THREAD

**Issue by pdoak** [Shougo/neosnippet.vim#268]
When I try to edit a snippet with `:NeoSnippetEdit`, I get the error message "Snippet directory is not found. Why is that?

Also, if I want to create my own snippets, can I do that on the fly and is so how? I tried using `:NeoSnippetSource` but I get "Argument required"

Also, the docs say to install context_filetype.vim. If I am using Vundle, do I just put Plugin 'Shougo/context_filetype.vim' in my list of plugins?

Many Thanks

Paul

**Comment by pdoak** [comment]
I realised I had to set a user snippet directory with
`let g:neosnippet#snippets_directory="/Users/pdd/.yadr/vim/MyNeoSnippets"` and now I can create custom snippets. 

Is it possible to create a snippet which executes bash commands?

**Comment by Shougo** [comment]
Yes.  It is feature.

> Is it possible to create a snippet which executes bash commands?

```vim
Vim has a built-in expression evaluation. You can also use this feature inside
of snippets if you use back ticks like in the example below. Here the "%:t"
gets expanded to the name of the current active file and the current time gets
inserted by expanding the output of the strftime command.

	snippet     header
	   File: ${1:`expand('%:t')`}
	   ${2:Created at: `strftime("%B %d, %Y")`}
```

You can use system function.
