### ISSUE TITLE
:NeoSnippetClearMarkers でエラー

### ISSUE THREAD

**Issue by thinca** [Shougo/neosnippet.vim#273]
help の FAQ に以下のような設定例があり、これを使用しているのですが、

```vim
autocmd InsertLeave * NeoSnippetClearMarkers
```

unite.vim の unite-file などで、挿入モードでディレクトリに対して `<CR>` などの操作をすると、以下のようなエラーが発生します。

```
function neosnippet#commands#_clear_markers..neosnippet#view#_search_snippet_range の処理中にエラーが検出されました:
行   18:
E21: 'modifiable' がオフなので, 変更できません
```

`'modifiable'` がオフの際に起きるので、unite.vim のように特殊な動作をするプラグインでしか起きないものかと思いますが、普段からこのエラーで結構困っているので報告させてもらいました。

**Comment by Shougo** [comment]
修正しました

**Comment by thinca** [comment]
修正を確認しました。ありがとうございます！
