### ISSUE TITLE
Snippets not working

### ISSUE THREAD

**Issue by Paludan** [Shougo/neosnippet.vim#275]
Hello Shougo, I am experiencing an issue. I'm currently using these addons: http://i.gyazo.com/a54baf2e3c1de28e007446a232014295.png

My issue is, that the snippets aren't inserting text when I select and hit enter (or tab): http://i.gyazo.com/58e27637899dac7b36eb724058691718.png

**Comment by Shougo** [comment]
```
:help <Plug>(neosnippet_expand_or_jump)
```

**Comment by Paludan** [comment]
That command does not seem to work.

**Comment by Shougo** [comment]
It is not command.  Your neosnippets usage is wrong.

```vim
	" SuperTab like snippets' behavior.
	imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
	 \ "\<Plug>(neosnippet_expand_or_jump)"
	 \: pumvisible() ? "\<C-n>" : "\<TAB>"
	smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
	 \ "\<Plug>(neosnippet_expand_or_jump)"
	 \: "\<TAB>"
```

You should see the documentation.
