### ISSUE TITLE
How can I disable snippets in '_.snip' only?

### ISSUE THREAD

**Issue by rhysd** [Shougo/neosnippet.vim#276]
neosnippet と neosnippet-snippets を使っています．

ファイルタイプ `vim` のときに `vim.snip` に書かれたスニペットを使いたいのですが，`_.snip` に書かれたスニペットは使いたくないです．

```vim
let g:neosnippet#disable_runtime_snippets = {'_' : 1, 'vim' : 0}
```

という設定をしてみたのですが，これは「ファイルタイプ `vim` のときのみスニペット読み込みを許可する」という意味になり，ファイルタイプ `vim` では `_.snip` のスニペットが候補に出てしまいました．（e.g. `path`）

良い方法はありませんでしょうか？

**Comment by Shougo** [comment]
確かに、`g:neosnippet#disable_runtime_snippets` は内部的に snippet directory を変更するだけなので、こんかいの用途には使えません。

機能追加するしかないのですが、内部的に `_.snip` は強制的に読み込まれており、
これを無効にする場合はユーザーの作成した `_.snip` も読み込まれなくなります。
それでも良いのなら実装しますが……。

**Comment by rhysd** [comment]
いえ，新規機能を実装してほしいという話ではなくて，現状できるかどうかを聞きたかっただけでした．
こちら側でやりようはあるので，追加実装していただかなくても大丈夫です．
ありがとうございます．
