### ISSUE TITLE
プレースホルダ文字列をconcealend に含めないようにするオプションがほしい。

### ISSUE THREAD

**Issue by LeafCage** [Shougo/neosnippet.vim#279]
Yggdroot/indentLine を使っていて気がついたことなのです。
このプラグインは cchar をつかってインデントレベルを表示させるものです。
このプラグインが有効の場合、neosnippetでスニペットを展開したときのプレースホルダが非表示になり、
カーソル表示と実際のカーソル位置がずれて表示されてしまいます（これはVimの問題っぽいですが）。

このプラグインはオプションを conceallevel=2 concealcursor=inc に設定してしまうのですが、そのせいでプレースホルダが隠されてしまうのが問題のようです。
neosnippet のプレースホルダは `autoload/neosnippet/init.vim` にて、concealend されるようになっておりますが、これを無効にするようなオプションを検討していただけないでしょうか？

**Comment by Shougo** [comment]
オプションを追加しました
