### ISSUE TITLE
Expanding a snippet inside another one breaks jump order!

### ISSUE THREAD

**Issue by dNItro** [Shougo/neosnippet.vim#280]
Say i have got a snippet, for Example:
```
snippet first
     ${1} ${2} ${3} ${4} ${5};
```
and another snippet like this:
```
snippet second
    ${1} ${2} ${3}
```
I mapped neosnippet expand and jump to **Tab** key:`imap <Tab> <Plug>(neosnippet_expand_or_jump)`
So when i type `name<Tab>` i get *<\`1\`> <\`2\`> <\`3\`> <\`4\`> <\`5\`>*; Then in the first placeholder i type `second<Tab>` *<\`2\`> <\`3\`> <\`4\`> <\`5\`>*, so i have *__<\`1\`> <\`2\`> <\`3\`>__ <\`2\`> <\`3\`><\`4\`> <\`5\`>*; Now when i am on the third placeholder of second snippet and use Tab key to jump over to next placeholder, it jumps to fourth place holder of first snippet! whereas it should jump to second placeholder of first snippet.

**Comment by Shougo** [comment]
Unfortunatelly, it is feature.
Neosnippet cannot understand it.
