### ISSUE TITLE
python interpolation

### ISSUE THREAD

**Issue by pwntester** [Shougo/neosnippet.vim#285]
Hi,

Im currently using ultisnips+neocomplete, although I would love to move to neosnippets. The only thing stopping me to do so is that I have some snippets that use the ultisnips python interpolation capabilities. Are there any plans to add that to neosnippets in the future?

Thanks,
A

**Comment by ujihisa** [comment]
Which does "python interpolation capabilities" mean?

a. default snippets for python (https://github.com/Shougo/neosnippet-snippets)
b. not only being able to insert Vim script expr in snippet but also `if_python` expr

**Comment by pwntester** [comment]
Its explained in this vimcast: http://vimcasts.org/episodes/ultisnips-python-interpolation/

In short, I would like to run python code to fill some of the snippet placeholders. In my case I need to generate a UUID for each snippet

**Comment by Shougo** [comment]
Unfortunatelly, neosnippet does not have (and I don't want to implement) the feature.
But, you can embed VimL code in neonsippet's snippets.
You can use if_python feature.
Closing.

**Comment by ujihisa** [comment]
s/VimL/Vim script/

**Comment by ujihisa** [comment]
Yes the python interpolation design looks more complicated than it should be, and the current neosnippet's Vim script placeholder is much more readable and succinct. No need for the special notation just for python.

**Comment by Shougo** [comment]
@pwntester I can implement the feature.  But it is limited than UltiSnips.
Because, neosnippet is not UltiSnips.

For example:

* neosnippet can implement `!p` but it is like py3eval().

* "global" ~ "endglobal" is hard to implement.  I think it should be include_python statement.

* snip.rv, t[1], t[2], ... cannot be implemented.

Do You need this feature?

**Comment by pwntester** [comment]
I need it for my snippets since I need to inject UUIDs in some of them. My current use in UltiSnips is like:

```
global !p
import uuid
def _get_rule_id():
    return str(uuid.uuid4()).upper()
endglobal

snippet RulePack "RulePack Template" b
<?xml version="1.0" encoding="UTF-8"?>
<MyTag>
    <MyTagID>`!p if snip.c == "": snip.rv = _get_rule_id()`</MyTagID>
    ....
</MyTag>
endsnippet
```

I can live without the global/endglobal as long as I can import a module and run a function in each snippet.

Thanks for considering adding the feature.

**Comment by Shougo** [comment]
Unfortunatelly, I cannot support `snip.c` feature.
You can use `pyeval()` like this in current neosnippet.

```
<?xml version="1.0" encoding="UTF-8"?>
<MyTag>
    <MyTagID>`=pyeval("_get_rule_id()")`</MyTagID>
    ....
</MyTag>
```

**Comment by pwntester** [comment]
oh, so thats currently supported? Where do I have to define _get_rule_id()?

**Comment by Shougo** [comment]
You can define it in your .vimrc.

```vim
pyfile some_file
```
or
```vim
python <<EOF
...
EOF
```

**Comment by Shougo** [comment]
I have implemented `source` feature.
You can load the Vim script file from the snippet.

**Comment by pwntester** [comment]
Hi,

I tried implementing new snippets using the python interpolation and unfortunately it is not working. Snippet looks like:

```
snippet StructuralRule
    <UUID>`=pyeval("import uuid;str(uuid.uuid4()).upper()")`</UUID>
```

But I get an error:

```
Error detected while processing function <SNR>191_snippets_expand_or_jump[1]..<SNR>191_snippets_expand[15]..neosnippet#view#_expand[20]..neosnippet#view#_insert[7]..<SNR>209_eval_snippet:
line   11:
E15: Invalid expression: =pyeval("import uuid;str(uuid.uuid4()).upper()")
E15: Invalid expression: =pyeval("import uuid;str(uuid.uuid4()).upper()")
```

Im using latest version of neovim and neosnippet.

Am I doing anything wrong?

Thanks,
A

**Comment by Shougo** [comment]
OK.  I get it.

It must be:

```vim
snippet StructuralRule
    <UUID>`pyeval("import uuid;str(uuid.uuid4()).upper()")`</UUID
```

**Comment by Shougo** [comment]
The feature will be supported in deoppet.nvim.
But the syntax may be changed.
