### ISSUE TITLE
using ultisnips and neosnippet at the same time

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/neosnippet.vim#286]
hey @Shougo  i have a lot of snippet write using python interpolation in ultisnips  i wont to use neosnippet and ultisnips at the same time how can i deal with that

**Comment by ujihisa** [comment]
https://github.com/Shougo/neosnippet.vim/issues/285

**Comment by 7belrhalmia** [comment]
@ujihisa  no i wont to use neosnnipet and ultisnips at the same time because when i install neosnippet and ultisnips neosnippet dosen't work

**Comment by ujihisa** [comment]
Do you mean you don't want to mix ultisnips and nepsnippet together, so you are implying to add a doc for that?

**Comment by 7belrhalmia** [comment]
no i want to mix them using ultisnips and neosnippet at the same time

**Comment by ujihisa** [comment]
Can you update the issue description to the statement you mentioned here? They seem completely opposite, which confuses us :D

**Comment by 7belrhalmia** [comment]
@ujihisa  do you have a solution

**Comment by Shougo** [comment]
No.  I don't want to support it.
They are same feature plugins.
It conflicts.

You can create it in UltiSnips issue.  I think it will be denied.

**Comment by 7belrhalmia** [comment]
@Shougo  most of users are not familliar with Viml language so they can write a very costum snnipet in neosnippet like they do for ultisnips because it support python  , in honza snippets the snippets for ultisnips are more powerful  how we can write like this snippet for neosnippet

**Comment by ujihisa** [comment]
s/Viml/Vim script/
