### ISSUE TITLE
expand snippet with enter key <cr>

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/neosnippet.vim#287]

**Comment by Shougo** [comment]
Please describe you wanted behavior.
It is not just expand snippet, is it?
I have not ESP.

**Comment by 7belrhalmia** [comment]
i have done this mapping  : 
     imap <expr><silent><TAB>    neocomplete#mappings#close_popup() .
      \ "\<Plug>(neosnippet_jump_or_expand)"

tab key work to trigger neosnnipet but dosen't work to jump between tabstop (tab key work just for expands nothing else)

**Comment by 7belrhalmia** [comment]
@Shougo  or even more when i do
imap < expr >< silen t>L neocomplete#mappings#close_popup() .
\ "<Plug>(neosnippet_jump_or_expand)"

than L key dosn't work any more for typing

**Comment by ujihisa** [comment]
They are independent to `<cr>` key

**Comment by Shougo** [comment]
> than L key dosn't work any more for typing

Yes.  you should use other keys like `<C-l>`.

> They are independent to <cr> key

Yes, ...

**Comment by 7belrhalmia** [comment]
there is no way to get that work because it will be awesome that when neocomplete show snippet they expand with enter < cr>

**Comment by Shougo** [comment]
@7belrhalmia You must define smap.

```vim
imap <expr><silent><TAB>    neocomplete#mappings#close_popup() .
      \ "\<Plug>(neosnippet_jump_or_expand)"
smap <silent><TAB> <Plug>(neosnippet_jump_or_expand)
imap <expr><silent><CR>    neocomplete#mappings#close_popup() .
      \ "\<Plug>(neosnippet_jump_or_expand)"
smap <silent><CR> <Plug>(neosnippet_jump_or_expand)
```

**Comment by 7belrhalmia** [comment]
@Shougo  the same problem

**Comment by 7belrhalmia** [comment]
when we do those mapping < tab> and < cr> work fine for autocompletion and neosnippet but tab key will not work in insert mode as a simple tabe key ,  if there is a possibility  for <cr > key to expand snippet from neocomplete and also work in insert mode as line return

**Comment by Shougo** [comment]
> when we do those mapping < tab> and < cr> work fine for autocompletion and neosnippet but tab key will not work in insert mode as a simple tabe key , if there is a possibility for key to expand snippet from neocomplete and also work in insert mode as line return

You should read neosnippet documentation....

`:help neosnippet#expandable_or_jumpable()`
