### ISSUE TITLE
Neosnippet doesn't work when snippet name is complemented

### ISSUE THREAD

**Issue by pocke** [Shougo/neosnippet.vim#288]
88d5efde1505bdd0f6c37e78892ae4887d2722b1 から発生しています。

スニペットの名称を補完を使用して入力すると、一部のスニペットがうまく展開されません。
例えば、c.snip の while https://github.com/Shougo/neosnippet-snippets/blob/master/neosnippets/c.snip#L31-L35 など
正常に展開されるスニペットもあるようですが、どのようなものが正常に展開されるのかはわかりませんでした。

再現手順
-----------

.vimrc

```vim
if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))


  NeoBundle     'Shougo/neocomplete'
  NeoBundle     'Shougo/neosnippet'
  NeoBundle     'Shougo/neosnippet-snippets'
call neobundle#end()

  let g:neocomplete#enable_at_startup = 1
  inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<S-TAB>"

  imap <silent><C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)


syntax enable
```

vimを起動し、以下のコマンドを実行

`set ft=c<CR>iwhi<C-n><C-k>`

whileのスニペットが展開されるのを期待しますが、上記の手順では`while()`とバッファに表示されます。
また、`set ft=c<CR>iwhile<C-k>` と、スニペットの名称を補完なしで全て入力すると再現しないようです。

**Comment by Shougo** [comment]
修正しました

**Comment by pocke** [comment]
ありがとうございます!
