### ISSUE TITLE
Caching dynamically inserted prototypes?

### ISSUE THREAD

**Issue by svanharmelen** [Shougo/neosnippet.vim#291]
When using the example keymaps to get `SuperTab` like behaviour, it seems that after the first time you dynamically expand a function prototype, the next time it will expand it again using <TAB> instead of the key binding configured for completing an autocompletion suggestion (<S-TAB> in my case.

See the relevant key bindings:

```
imap <expr> <S-TAB> pumvisible() ?
 \ deoplete#mappings#close_popup() . "\<Plug>(neosnippet_expand_or_jump)"
 \ : "\<S-TAB>"

" SuperTab like snippets' behavior.
imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
 \ "\<Plug>(neosnippet_expand_or_jump)"
 \: pumvisible() ? "\<C-n>" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
 \ "\<Plug>(neosnippet_expand_or_jump)"
 \: "\<TAB>"
```

And here an example. I only press <TAB> to cycle through the list of possible completions in both cases. The first time it just keeps cycling until I hit <S-TAB>, but the second time it automatically expands when I hit the same snippet I already expanded once before with just hitting <TAB>:

![example](https://cloud.githubusercontent.com/assets/4171547/9566808/73f10718-4f13-11e5-84e4-e59e827237d1.gif)

So does it somehow caches the already used snippets so the next time it is recognised as a snippet?

**Comment by Shougo** [comment]
Yes.  It is feature.

**Comment by svanharmelen** [comment]
In that case I guess you should remove the example bindings from the docs, as they clearly will not work as advertised.

Thx...

**Comment by svanharmelen** [comment]
@Shougo just to be sure... I just noticed that in the original issue report the brackets around the word TAB were not escaped, so the referred key bindings did not show up in the report. Does that change your view to it being a bug in this specific use case? Or is it still a feature (and should the docs be updated instead)?

Thx!

**Comment by Shougo** [comment]
OK, I get it.
You should change the key mapping like this.

```
imap <expr><TAB> pumvisible() ? "\<C-n>" :
\ neosnippet#expandable_or_jumpable() ?
 \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
```

**Comment by Shougo** [comment]
Updated the documentation.

**Comment by svanharmelen** [comment]
@Shougo I will give it a try, but I guess that will give yet another bad side effect (different behavior). But I'll test it later and update with some examples and the result later on...

**Comment by svanharmelen** [comment]
@Shougo I know this is an old issue, but I was wondering if this should still work? I did not use snippets for a while, but am not trying to get this behaviour again. But whatever I try, I do not get the dynamic prototype snippets like discussed here.

I'm using (mainly):

```
deoplete.nvim
deoplete-go
neosnippet
vim-go
```

And have configured:

```
let g:neosnippet#enable_completed_snippet = 1
let g:neosnippet#disable_runtime_snippets = {'_' : 1}
```

I do get the snippets that come with `vim-go` and they expand and jump as expected. But I do not get the dynamic prototype snippets to work.

Any advice? Is something changed since the introduction of `deoplete-go` that could cause this?

Thanks!

**Comment by svanharmelen** [comment]
@Shougo ah, found it already... I needed to set `call deoplete#custom#set('_', 'converters', ['converter_auto_paren'])` in order to make it work.

**Comment by Shougo** [comment]
Yes.  It is needed.

**Comment by svanharmelen** [comment]
@Shougo is there any way to trigger `enable_completed_snippet` **only** when pressing a certain key binding? I find it very annoying that is always provides the dynamically generated snippet and would like to be able to call for it.

Say I am typing and I get a few autocomplete options from `deoplete` I press `<C-n>` a couple of times and then only when I type a specific keybinding I get the snippet. So if I don't use that specific keybinding I just use the autocomplete option as usual.

Would be really cool if I could use it like that, because having it always trigger is not making my life easier. Thanks!!

**Comment by Shougo** [comment]
I get it.  It should be.
Please create new issue for it.
