### ISSUE TITLE
Add support for anonymous snippet similar to UltiSnips

### ISSUE THREAD

**Issue by lervag** [Shougo/neosnippet.vim#293]
Hi. I'm currently using UltiSnips in my LaTeX plugin [vimtex](https://github.com/lervag/vimtex/). Specifically, I am using the function `UltiSnips#Anon` to create some utility mappings that are expanded automatically. For instance, I have this mapping (or at least something very similar):

```vimL
imap (( ((<C-R>=UltiSnips#Anon('\left($1\right)', '((', '', 'i')<CR>
```

This makes `((` automatically expand to `\left(|\right)` (`|` is cursor), and it allows to use the jump trigger to move the cursor out of the snippet. However, UltiSnips has a bug/problem where nested anonymous snippets break the jump trigger, see e.g. [#528](https://github.com/SirVer/ultisnips/issues/528). I was thinking that this might work in neosnippet, or that you might perhaps add this feature. If you did, then I would gladly use neosnippet as the snippet backend for my plugin.

**Comment by Shougo** [comment]
OK.  It seems new feature.
But I can implement it.

**Comment by lervag** [comment]
Great, that makes me very happy! :)

**Comment by Shougo** [comment]
Hi, I tested for nested snippets in neosnippet.
neosnippet supports nested snippets.

But I found some notices.

* You must use option "word" to expand nested snippet

* You must use `<Plug>(neosnippet_expand_or_jump)` mapping

**Comment by Shougo** [comment]
Implemented.

Example:

```vim
inoremap <silent> (( ((<C-r>=neosnippet#annonymous('\left(${1}\right)${0}')<CR>
```

**Comment by Shougo** [comment]
It supports nested snippet expansion.

Note:  The snippet syntax is different from UltiSnips.
But it is better than create your minimal snippet engine :-)

**Comment by lervag** [comment]
Great, thanks! A couple of questions:

1. For `UltiSnips#Anon`, the preceding `((` was necessary for the snippet expansion. It seems this is not necessary with `neosnippet#anonymous`, i.e. it seems the mapping is simply

        inoremap <silent> (( <C-r>=neosnippet#annonymous('\left(${1}\right)${0}')<CR>

    This makes me think it could be (or should be) possible to simplify even further, to:

        inoremap <expr><silent> (( neosnippet#annonymous('\left(${1}\right)${0}')

    However, this does not seem to work. I get an error as follows:

        Error detected while processing function neosnippet#annonymous[1]..neosnippet#mapp
        ings#_annonymous[5]..neosnippet#view#_insert:
        line   48:
        E523: Not allowed here

2. The snippet syntax is different, in that it uses `${1}` instead of `$1` and requires the `${0}` at the end. I can accept this, as it seems to be easy to create a mapping between the two syntaxes. However, I was wondering what you mean with the notice about the `word` option. Do you mean that the word option is implicitly used for anonymous snippets?

**Comment by lervag** [comment]
A minor comment: The name should be `neosnippet#anonymous` (only 1 'n' after the 'a').

**Comment by Shougo** [comment]
> For UltiSnips#Anon, the preceding (( was necessary for the snippet expansion. It seems this is not necessary with neosnippet#anonymous, i.e. it seems the mapping is simply

Thank you.  Fixed the example in doc.

> However, this does not seem to work. I get an error as follows:

No.  It is invalid.  Because, it moves cursor and changes the buffe.
Please see `:help map-<expr>`

```
Be very careful about side effects!  The expression is evaluated while
obtaining characters, you may very well make the command dysfunctional.
For this reason the following is blocked:
- Changing the buffer text |textlock|.
- Editing another buffer.
- The |:normal| command.
- Moving the cursor is allowed, but it is restored afterwards.
If you want the mapping to do any of these let the returned characters do
that.
```

**Comment by Shougo** [comment]
> The snippet syntax is different, in that it uses ${1} instead of $1 and requires the ${0} at the end. I can accept this, as it seems to be easy to create a mapping between the two syntaxes. However, I was wondering what you mean with the notice about the word option. Do you mean that the word option is implicitly used for anonymous snippets?

No.  It is not needed.  The "word" option works for expanding snippet trigger.

> A minor comment: The name should be neosnippet#anonymous (only 1 'n' after the 'a').

Thank you.  Fixed.

**Comment by lervag** [comment]
Thanks for clearing up the `<expr>` thing. And great work! Again thanks!

**Comment by Shougo** [comment]
I have added `map-<expr>` support in `neosnippet#anonymous()`.

**Comment by lervag** [comment]
Thanks! This just becomes more and more useful!
