### ISSUE TITLE
compatible doesn't work in lastest version

### ISSUE THREAD

**Issue by wewea** [Shougo/neosnippet.vim#295]
part of .vimrc
```vim
let g:neosnippet#enable_snipmate_compatibility = 1
let g:neosnippet#snippets_directory='~/.vim/bundle/vim-snippets/snippets'
```
it is used to work. but after PluginUpdate, it couldn't recognize file type of vim-snippets.
only if i modified the snip filename from javascript.node.snippets to node.snip, then it work as usual.

i also try cpp file, it get the same problem.

**Comment by Shougo** [comment]
Thank you.  Fixed.
