### ISSUE TITLE
Error Prints On Invalid Mapping

### ISSUE THREAD

**Issue by j5shi** [Shougo/neosnippet.vim#296]
Though I am not affected by this error print, I think it's better to fix it. The following log was printed many times at vim startup.

`Error detected while processing function neosnippet#mappings#_clear_select_mode_mappings:`
`line   13:`
`E31: No such mapping`

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please create minimal .vimrc less than 50 lines and the reproduce ways from Vim starting.

**Comment by Shougo** [comment]
And please up

**Comment by j5shi** [comment]
It disappeared after updating `neosnippet`, I used this way to find that error prints:

```
set verbosefile=$VIM/VimRuntimeDebugging.log
set verbose=2
```

As it's disappeared, I'll close it.

**Comment by Shougo** [comment]
OK
