### ISSUE TITLE
Expand snippet from mapping

### ISSUE THREAD

**Issue by lervag** [Shougo/neosnippet.vim#297]
I am wondering if (1) it is possible to expand a snippet from a mapping, or (2) you could add this functionality to neosnippet.

Consider the following snippet:

```
snippet test
options head
        `strftime("%Y-%m-%d")`
```

I want to create a mapping:

```vimL
nnoremap ,t i<c-r>=neosnippet#expand('test')<cr>
```

or alternatively:

```vimL
nmap test itest<plug>(neosnippet_expand)
```

Note that I really want the map to start from normal mode.

This is quite similar to the `neosnippet#anonymous(...)` functionality (see #293), only I want it for already existing snippets.

**Comment by lervag** [comment]
After testing, it seems this almost work already. However, I need to define the map with an extra space:

```vimL
nmap test itest <plug>(neosnippet_expand)
```

Still, I think it would be useful with the function approach in my first example, if it is possible.

**Comment by Shougo** [comment]
It seems new feature.

**Comment by Shougo** [comment]
I have added `neosnippet#expand()`.

**Comment by lervag** [comment]
Thanks! I've found a minor bug. Consider the snippet:

```
snippet test
options head
        ${1:test}
```

and the mappings:

```vimL
nnoremap <silent> ,n i<c-r>=neosnippet#expand('test')<cr>
nnoremap <silent> ,m :call neosnippet#expand('test')<cr>
```

Here the mapping `,n` that uses `neosnippet#expand` from insert mode does not work as expected, while `,m` works well. It seems `,n` does not return a selection over `test`.

**Comment by Shougo** [comment]
Fixed.

**Comment by lervag** [comment]
Thanks! I REALLY like that I can use the mapping with `<expr>`, I think that might become very useful. Great work!
