### ISSUE TITLE
scope aliases undefined in neovim

### ISSUE THREAD

**Issue by alnjxn** [Shougo/neosnippet.vim#300]
Using Neovim I am attempting to enable html snippets inside of javascript/jsx file types for use with React. Adding the following in my init.vim
`let g:neosnippet#scope_aliases['javascript'] = 'html,javascript'`
I get the following error 
`E121: Undefined variable: g:neosnippet#scope_aliases`

Is this syntax correct? Should I be enabling this using omnifunc instead? Thanks!

**Comment by Shougo** [comment]
You must initialize `g:neosnippet#scope_aliases` variable.
It is VimL feature.

```vim
let g:neosnippet#scope_aliases = {}
let g:neosnippet#scope_aliases['javascript'] = 'html,javascript'
```
