### ISSUE TITLE
Error detected while processing function neosnippet#init#_initialize

### ISSUE THREAD

**Issue by mtglsk** [Shougo/neosnippet.vim#301]
Error detected while processing function neosnippet#init#_initialize[4]..<SNR>10
    7_initialize_cache[2]..neosnippet#commands#_make_cache[19]..neosnippet#parser#_p
    arse_snippets[11]..<SNR>117_writefile:
    line    3:
    E482: Can't create file /home/<USER>/.cache/neosnippet/=+home=+<USER>=+.vim=+plugged=+ne
    osnippet-snippets=+neosnippets=+_.snip

Ad nauseam

**Comment by Shougo** [comment]
I think your `USER/.cache` or `USER/.cache/neosnippet` permissions are not writable.
My ESP skill result:  You have executed `sudo vim` and created not writable directories.
Please upload `ls -l` result in them.

**Comment by mtglsk** [comment]
Yeah, i figured it out. It's weird because i haven't run vim-plug plugupdate with root / sudo, so i think this shouldn't happen. Maybe some previous sudo command caused subsequent commands to run with admin rights. Closing the issue.

**Comment by Shougo** [comment]
OK.

**Comment by coljiang** [comment]
@Shougo ，thank you very much , i have this error ,as you say， i fixed this error
