### ISSUE TITLE
snippet jump error.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neosnippet.vim#302]
java.snips
```
snippet     cle
abbr        cle
alias       class
options     head
    public class ${1:`expand('%:t:r')`} ${2:extends ${3:parentClass\}} ${4:implements ${5:interfaces\}} {
        ${0}
    }
```
when I jump to ${2},i type backspace, then can not jump to ${4} and ${5},but if i jump to ${3},them type backspace ,everything will be ok,i think it is because after ${2},if i type backspave,the plugin can not find ${3},so jump to ${0} directly

**Comment by Shougo** [comment]
Fixed.

**Comment by wsdjeg** [comment]
works nice ,thanks
