### ISSUE TITLE
after complete vim script will get extra pairs

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neosnippet.vim#304]
hi @Shougo 
i hava test the latest version neosnippet,if we use deoplete complete an no args vim script ,will get an extra pair
let g:neosnippet#enable_complete_done = 1

here is the pic
![2015-12-13 13-02-35](https://cloud.githubusercontent.com/assets/13142418/11765625/d9e5e1fe-a19a-11e5-91d7-389e1f90a398.png)
type c-y or enter or esc
![2015-12-13 13-02-41](https://cloud.githubusercontent.com/assets/13142418/11765658/d1b8f150-a19b-11e5-86b2-9542f01538ca.png)

**Comment by Shougo** [comment]
I think it is bug.
But please provide the minimal .vimrc and reproduce ways.

Note:  Your .vimrc is always not minimal.
Please read the issue template.

https://github.com/Shougo/neocomplete.vim/issues/236

**Comment by wsdjeg** [comment]
i have create a neosnippet test branch 
https://github.com/wsdjeg/DotFiles/blob/neosnippet-test/vimrc
all vimrc in one screen

**Comment by Shougo** [comment]
OK.  Reproduce it in the latest neosnippet?
Please test it.

**Comment by wsdjeg** [comment]
how fast your push,let me have a try.

**Comment by wsdjeg** [comment]
still get the same issue

**Comment by Shougo** [comment]
OK, I will test it.
Please upload the .vim file.

**Comment by wsdjeg** [comment]
```vim
let g:python_host_prog = '/usr/bin/python'
let g:python3_host_prog = '/usr/bin/python3'

"setup & neobundle {{{
if has('vim_starting')
	if &compatible
		set nocompatible
	endif
	set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle/'))
scriptencoding utf-8
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/deoplete.nvim'
let s:hooks = neobundle#get_hooks("deoplete.nvim")
function! s:hooks.on_source(bundle)
	let g:deoplete#enable_at_startup = 1
	inoremap <silent> <expr><CR> pumvisible() ? "\<C-y>" : "\<cr>"
	inoremap <expr><C-h> deolete#mappings#smart_close_popup()."\<C-h>"
	inoremap <expr><BS> deoplete#mappings#smart_close_popup()."\<C-h>"
endfunction
NeoBundle 'Shougo/neco-syntax'
NeoBundle 'Shougo/neco-vim'
if !exists('g:necovim#complete_functions')
	let g:necovim#complete_functions = {}
endif
let g:necovim#complete_functions.Ref =
			\ 'ref#complete'
NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'Shougo/neosnippet.vim' "{{{
let g:neosnippet#snippets_directory='~/DotFiles/snippets'
let g:neosnippet#enable_snipmate_compatibility=1
let g:neosnippet#enable_complete_done = 1
imap <expr><TAB> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : (pumvisible() ? "\<C-n>" : "\<TAB>")
smap <expr><TAB> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
imap <expr><S-TAB> pumvisible() ? "\<C-p>" : ""
smap <expr><S-TAB> pumvisible() ? "\<C-p>" : ""
call neobundle#end()
filetype plugin indent on
syntax on
function MyTest()

endf
```
then you can try with  complete call MyTest()

**Comment by wsdjeg** [comment]
i have test the laterst version ,i find it works well ,but i well test more about other language

**Comment by Shougo** [comment]
OK.
