### ISSUE TITLE
Can't load my custom snippets

### ISSUE THREAD

**Issue by yusiwen** [Shougo/neosnippet.vim#307]
Thanks for your great work, it's really a great time-saving plugin!

After trying neosnippet for a few days, I want to add some my custom snippets to it. So, first I added this to my `.vimrc`:

```
let g:neosnippet#snippets_directory='~/myConfigs/vim/snippets'
```

Under the directory `~/myConfigs/vim/snippets`, I created a file `custom.snip`:

```
# Custom Test Snippets

snippet     date_normal
abbr        dn
options     word
    `strftime("%Y-%b-%d")`${0}
```

After restarting vim, when I type 'date_normal`, this custom snippet is not shown in the popup menu. Did I miss something?

Sorry for my noob question.

**Comment by Shougo** [comment]
> Under the directory ~/myConfigs/vim/snippets, I created a file custom.snip:

The "custom.snip" is loaded in custom filetype only.
It is same behavior with snipMate.
If you need the snippet in all filetypes, you should create `_.snip`.

**Comment by yusiwen** [comment]
Oh, I see. Thanks, you are my savior!
