### ISSUE TITLE
Can neosnippet expand the first candidate when <C-k> is pressed even if the snippet name is not fully typed?

### ISSUE THREAD

**Issue by yusiwen** [Shougo/neosnippet.vim#310]
Thanks for your great work!
But I've encountered some problem recently. For example, there is an snippet called `vim-modeline`, after I'm typing 'vim', the popup menu shown up with the right snippet selected (highlighted). But at this point when I press <C-k>, the selected snippet can't expand. It's only expandable after I've fully typed the snippet's name. I think this situation is awkward, because the snippet I want to expand is already selected by the popup menu, but still I must type it fully before I can expand it. 

Can it be expanded even if I haven't typed the whole name when it is selected by the popup menu?

There is my settings:

```
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)

" SuperTab like snippets behavior.
imap <expr><TAB>
      \ pumvisible() ? "\<C-n>" :
      \ neosnippet#expandable_or_jumpable() ?
      \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ? "
      \<Plug>(neosnippet_expand_or_jump)"
      \: "\<TAB>"

" For conceal markers.
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
```

Thanks a lot!

**Comment by Shougo** [comment]
```vim
imap <expr><C-k> (pumvisible()? "\<C-y>" : '') . "\<Plug>(neosnippet_expand_or_jump)"
```

**Comment by yusiwen** [comment]
Thanks.
