### ISSUE TITLE
.snippetのスニペットが読み込まれない

### ISSUE THREAD

**Issue by svjunic** [Shougo/neosnippet.vim#311]
自然に使いすぎて気づかなかったのですが、.snippetの拡張子のスニペットが読み込まれなくなっているようです。

以前は使えていたので、どこかで変わったのだと思います。
helpは変わっていないようでしたので、一度ご確認いただけないでしょうか。

```
"vim.snip*"
"vim_*.snip*"
"vim/**/*.snip"
```

下記のスニペットで試しました。
https://github.com/svjunic/svjunic-snip/blob/master/snippets/javascript.snippet

```
let g:neosnippet#snippets_directory = '~/.vim/bundle/svjunic-snip/snippets'
```

javascript.snippet
-> 読み込まれない

javascript.snip
-> 読み込まれる

**Comment by Shougo** [comment]
これはファイル名が不正だからです。
.snip (neosnippet 方式), もしくは .snippets (snipMate 方式) のファイル名しか読み込まなくなりました。
拡張子を変更してください。

**Comment by Shougo** [comment]
ドキュメントを修正しました

**Comment by svjunic** [comment]
ありがとうございます。
ファイル名変更で対応します。
