### ISSUE TITLE
Invalid Code Indent

### ISSUE THREAD

**Issue by joywek** [Shougo/neosnippet.vim#312]
I have writen a javascript snip as following:

```
snippet rcc
    var React = require('react')

    var ${1} = React.createClass({

        render: function() {
            return (
                <div />
            );
        }

    });

    module.exports = $1
```

When I use `C-k` completes the snip, the code format is unexpected(there addtional indent):

![snip](https://github.com/joywek/resources/blob/master/snip.png?raw=true)

**Comment by Shougo** [comment]
I cannot reproduce the problem.
I use "simple-javascript-indenter".
It depends on your javascript indentation plugin behavior.
Because, neosnippet uses indentation plugin.
If you don't like the behaviour, you can use `<Tab>` characters instead of spaces.
