### ISSUE TITLE
Snippets not matching after a period

### ISSUE THREAD

**Issue by jonahx** [Shougo/neosnippet.vim#313]
Eg, ruby's `reduce` method (from a honza snippet) appears fine when typed after a space: 
![reduce works](http://i.imgur.com/alMnshv.png)

But fails to appear after a `.`:
![reduce works](http://i.imgur.com/IRvLwJP.png)

Is there a config option I can use to make it appear after a period as well?  Anything I can do?

Thanks.

**Comment by Shougo** [comment]
`:help g:neosnippet#enable_word_boundary`

**Comment by jonahx** [comment]
I have tried setting it to both the values `0` and `1`, but either way the problem in my OP persists.  Sorry, but the help entry is as follows, so I can't figure out what I'm doing wrong:

```
g:neosnippet#expand_word_boundary
		If it is not 0, neosnippet will expand snippets by a word
		boundary.
		Note: It must be initialized before snippet loading.

		The default value is 0.
```

**Comment by Shougo** [comment]
@jonahx 

1. Please update neosnippet
2. Execute `NeoSnippetMakeCache` in ruby files

You must re-make cache file.

**Comment by jonahx** [comment]
Working now.  Thanks very much!

**Comment by GuillaumeLeclerc** [comment]
It helped me a lot too, Thanks !
