### ISSUE TITLE
completed snippet behavior need to fix

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neosnippet.vim#318]
hello @Shougo ,happy new year!
now I am using neosnippet.vim auto expand my complete item from omni,but some strange things happend.here is my example:
![2015-12-31 20-51-48](https://cloud.githubusercontent.com/assets/13142418/12064548/c1fa9e58-b000-11e5-8508-ecc88766e018.png)
you see ,the complete method name is `getDeclaringClass()`,has no args,the `java.lang.Object<?>` is the retuen type of this method;
but after type Enter i got
![2015-12-31 20-51-54](https://cloud.githubusercontent.com/assets/13142418/12064581/5a333f22-b001-11e5-831b-67a28c34d32c.png)
I think the `<?>` has beed expanded ,that is not what I want.
i think maybe the plugin should search for the complete word `getDeclaringClass`,and expand the args in the pairs behind this word;

**Comment by wsdjeg** [comment]
and if there is no `<>` or `<?>` or `<Something>` in the item,everything will be ok

**Comment by wsdjeg** [comment]
fixed by change 
https://github.com/Shougo/neosnippet.vim/blob/50a25a35a2dee284b32ab71f28046de3c51f57eb/autoload/neosnippet/parser.vim#L319
to
```
  if abbr =~ '<.\+>' && 0
```
i think there should be a g:var to defind what pairs is for current filetype

**Comment by Shougo** [comment]
Fixed.

**Comment by wsdjeg** [comment]
thanks ,works well
