### ISSUE TITLE
can not expand the args after completion

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neosnippet.vim#319]
hi @Shougo after the latest version,can not expand the args after completion ,here is an example
```java
class Foo{
  this._  //here is cursor,when i select the wait(long,int)
}
```
only get `this.wait(vlllong, #:int)#:int)`

vim test.vim 
type into call expand  tab

get 

` call expand(vllllllllllllllllllllllllllllexpr} [, {nosuf} [, {list}]])`2`>`

**Comment by Shougo** [comment]
Fixed.
