### ISSUE TITLE
expand the args after completion can not works well when there is ) after cursor.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neosnippet.vim#320]
os ubuntu 
nvim or vim ,deoplete or neocomplete,these two evn I hava tested both;

example
```java
class Foo{
   (_)  //_ is cursor
}
```
my cursor is in a pairs,then I type into `this.` will get the method of current class,

for example I choose `wait(long)`  the word is `wait(` the abbr is `want()` the menu is `void java.lang.Object.wait(long)`,by default I can expand the args successful,but if there is a `)` after my cursor,the auto expandding args does not work well,I think expand args should not care about any chars after cursor.

**Comment by wsdjeg** [comment]
I have reset to https://github.com/Shougo/neosnippet.vim/commit/57301f8a5d405c6c793c3b4d1a86f198dcdc81a9
and it works well ,so maybe something after this commit

**Comment by Shougo** [comment]
Fixed.

**Comment by wsdjeg** [comment]
thanks
