### ISSUE TITLE
Disable context_filetype for certain files

### ISSUE THREAD

**Issue by NigoroJr** [Shougo/neosnippet.vim#326]
## Summary
`c` ファイルでcontext_filetype.vimが使われるため、 `cpp` 用のスニペットもロードされる。

### vimrc

```vim
if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/context_filetype.vim', {
      \ 'lazy': 1,
      \ }
NeoBundle 'Shougo/neosnippet.vim'

let g:neosnippet#snippets_directory = '~/snippets'

imap <expr> <TAB> neosnippet#expandable_or_jumpable() ?
      \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

call neobundle#end()
filetype plugin indent on
```

### Snippets
```
# ~/snippets/c.snip
snippet		foo
	This is from c.snip
```

```
# ~/snippets/cpp.snip
snippet		foo
	This is from cpp.snip
```

1. `vim -u ~/vimrc foo.c`
2. `foo<Tab>` と入力する。
3. `This is from cpp.snip` と表示される。

## Expected
`This is from c.snip`と表示される。

## Note
neosnippet.vimで呼ばれる`context_filetype#get_filetypes('c')` で`['c', 'cpp']` が返されるためだと思われます。「 `*.c` ファイル(あるいは`&filetype` が `c` の場合)ではcontext_filetype.vimがインストールされていても使わない」というようなオプションがあると便利だと思うのですが、いかがでしょう？ 

上記vimrcでneobundle.vimを使っているのは、`'lazy': 1` でrtpに追加されていないはずなのに、スニペットを展開したあと追加されているというのがなぜかよく分からなったためです。

**Comment by Shougo** [comment]
これは context_filetype.vim の問題です。
直したので context_filetype.vim をアップデートしてください。

**Comment by NigoroJr** [comment]
ありがとうございました。修正確認しました。以前にも違うプラグインでissueを立ててしまってなんだか申し訳ないです :sweat:

**Comment by Shougo** [comment]
問題ないです
