### ISSUE TITLE
Multiple replacement is not working if Vim's word-wrap is applied during snippets completion

### ISSUE THREAD

**Issue by wikimatze** [Shougo/neosnippet.vim#328]
Hi Shougo,

I'm running the latest version of neosnippets and using the following snippet for editing markdown files:

```sh
snippet fancynormal
  <img src="${1:}" class="big center" alt="${2:}"/>
  <div class="caption">"$2"</div>
```sh


So I'm using this snippets to add an image. press `Tab` to edit the alt and caption in one stroke, they should have the same name. It's working fine, but the image URL is too long and my word-wrap settings for markdown files are applied 


```sh
setlocal ts=2 sw=2 expandtab textwidth=120
```

I can't edit the alt and caption part with one stroke when I press `Tab`. To see the issue please consult the following gif:

![output](https://cloud.githubusercontent.com/assets/264708/12865119/2a364444-cca4-11e5-80de-7901ac583cdf.gif)

**Comment by Shougo** [comment]
I get it.  But it is feature.

**Comment by wikimatze** [comment]
Okay. Can you make a feature request out of this or is it something that is not worth to be implemented?

**Comment by Shougo** [comment]
> Okay. Can you make a feature request out of this or is it something that is not worth to be implemented?

It is wired behavior.  But it is hard to fix it.

**Comment by wikimatze** [comment]
No problem, I think I will then just change the textwidth for markdown files because I often include long flickr URLs.
