### ISSUE TITLE
How to set noexpandtab for neosnippet filetype

### ISSUE THREAD

**Issue by zhuochun** [Shougo/neosnippet.vim#330]
I set `noexpandtab` for filetype neosnippet, however it is overwritten by `ftplugin/neosnippet.vim`.

Is there a way to solve this? Thanks.

```
" My config https://github.com/zhuochun/dotfiles/blob/master/vim/rc/filetypes.vim#L2
autocmd! FileType neosnippet,snippet setlocal noexpandtab
```

**Comment by Shougo** [comment]
Please create "after/ftplugin/neosnippet.vim"
