### ISSUE TITLE
Snippets Jump Failed After Recent Update

### ISSUE THREAD

**Issue by j5shi** [Shougo/neosnippet.vim#331]
Neosnippet configuration:

```vim
    let g:neosnippet#snippets_directory            = "$VIM/vimfiles/bundle/snippets"
    let g:neosnippet#disable_runtime_snippets      = {'_' : 1}
    let g:neosnippet#enable_snipmate_compatibility = 1

	imap <C-e> <Plug>(neosnippet_expand_or_jump)
	smap <C-e> <Plug>(neosnippet_expand_or_jump)
	xmap <C-e> <Plug>(neosnippet_expand_target)
```

Snippet:

```vim
snippet     class
abbr        class Class(...): ...
options     head
	class ${1:#:name}(${2:object}):
		               
		def __init__(self${3:#:, argument}):
			${0}
```

Output of `verbose imap <C-e>`

```vim
i  <C-E>         <Plug>(neosnippet_expand_or_jump)
	Last set from C:\Program Files (x86)\Vim\_vimrc
```

Symptom: in insert mode in a python script, type `class`, then press `<C-e>`, the snippet will be expanded, however, then press `<C-e`, all placeholders disappeared, and the cursor remains at the last position it was.

**Comment by j5shi** [comment]
This issue was cause by the incompatibility of `vim-auto-save`, issue closed, thanks.

https://github.com/907th/vim-auto-save

**Comment by gunar** [comment]
I have the same problem! I use both `neosnippet` and `vim-auto-save`. Did you solve it?

**Comment by gunar** [comment]
@Shougo, sorry to bother. Do you perhaps know how to solve this? :innocent: Thank you!

**Comment by Shougo** [comment]
@gunar `:help g:neosnippet#enable_auto_clear_markers`
