### ISSUE TITLE
Snippet with vim function can't work properly

### ISSUE THREAD

**Issue by j5shi** [Shougo/neosnippet.vim#332]
What I want to do is to convert `MixedCase` to `MIXED_CASE`, so I defined a snippet like this

```
UT_DEFINES += -D`toupper(substitute("$1", '\(.\)\(\u\)', '\1_\2', 'g'))`_UNIT_TEST
```

With `$1` == `HelloWorld`, I got expanded snippet:

```
UT_DEFINES += -DHelloWorld_UNIT_TEST
```

What I expect is

```
UT_DEFINES += -DHELLO_WORLD_UNIT_TEST
```

**Comment by Shougo** [comment]
You cannot expand `$1` in the block.

It is not supported.
https://github.com/Shougo/neosnippet.vim/issues/270
