### ISSUE TITLE
snipMate .snippet(s) not working

### ISSUE THREAD

**Issue by cj** [Shougo/neosnippet.vim#335]
I'm trying to get https://github.com/gevans/vim-ginkgo/tree/master/snippets/ginkgo to work with neosnippet.  I have `let g:neosnippet#snippets_directory .= $HOME.'/.vim/plugged/vim-ginkgo/snippets/ginkgo'` and when I run `echomsg "get_dir:".string(neosnippet#get_snippets_directory())` i get this `get_dir:['/home/cj/.vim/plugged/vim-ginkgo/snippets/ginkgo', '/home/cj/.vim/plugged/vim-go/gosnippets/snippets', '/home/cj/.vim/plugged/neosnippet-snippets/neosnippets', '/home/cj/.vim/plugged/vim-snippets/snippets', '/home/cj/.vim/plugged/vim-ginkgo/snippets']`.

Are those snipMate snippets just not compatible?

**Comment by cj** [comment]
I also forgot to mention I have `let g:neosnippet#enable_snipmate_compatibility = 1` too.

**Comment by Shougo** [comment]
@cj You must specify the snippets directory instead of `ginkgo` directory.

```vim
let g:neosnippet#snippets_directory .= $HOME.'/.vim/plugged/vim-ginkgo/snippets'
```

And the snippets is loaded when the filetype is `ginkgo`.
I think the directory name is wrong.  It should be `go` in go filetype.

**Comment by cj** [comment]
@Shougo thank you for the response. sorry, I should have mentioned I also tried that.  They still don't show.  ginkgo is correct, it's a test lib for go.  They set the type here https://github.com/gevans/vim-ginkgo/blob/master/ftdetect/ginkgo.vim#L2

**Comment by Shougo** [comment]
OK.  Please upload minimal .vimrc and reproduce ways from Vim starting.
