### ISSUE TITLE
Question: In placeholders, how can I expand another snippet?

### ISSUE THREAD

**Issue by ranranking** [Shougo/neosnippet.vim#336]
For example, I have two snippets :`A(${1})` and `B(${1})`. When I expanded snippet A, it shows `A()<'0'>`, and in the parenthesis, I try to expand snippet B, it was not working. When snippet A is `A(${1})${2}`, sometime I don't even have choice for snippet B at placeholder 2.  However, when snippet A is like this:

```vim
A(${1})
${2}
```

I still cann't have B expanded at placeholder 1, but at placeholder 2, I can finally expand B. So what is my problem? Is there any options I can set for this situation?

**Comment by Shougo** [comment]
Please read the documentation.

```
Q: What if I want to expand a snippet trigger after (, [, " etc...:

A: You should use "options word" in the snippet definition. This changes the
expansion behavior to a word boundary or set
|g:neosnippet#expand_word_boundary|.
>
	snippet     date
	options     word
	    `strftime("%d %b %Y")`
<
```
