### ISSUE TITLE
extra snippets directory creation interferes with neobundle

### ISSUE THREAD

**Issue by sdx23** [Shougo/neosnippet.vim#337]
Directories added to `g:neosnippet#snippets_directory` will be created automatically, if they don't exist. This interferes with neobundle, which will consider the corresponding snippets-"plugin" already installed, as the directory exists then.

What motivated this behaviour? It seems rather non-sensible, so I'd guess I missed something - otherwise this'd be a PR...

**Comment by Shougo** [comment]
Please describe the example.
I cannot understand why neosnippet interferes with neobundle.

**Comment by sdx23** [comment]
Lets say I want to include Honzas snippets (as suggested in the Readme), then I'd edit my .vimrc to add

    NeoBundle 'honza/vim-snippets'

in the neobundle-section, and somewhere below

    let g:neosnippet#snippets_directory='~/.vim/bundle/vim-snippets/snippets'

What happens now is: neosnippet gets loaded, searches for that directory, doesn't find it and creates it for some reason (hoped you'd tell me). After that, neobundle searches for directories of plugins, finds 'vim-snippets' is already there and doesn't install it.

**Comment by Shougo** [comment]
OK.  I get it.
