### ISSUE TITLE
possible to `NeoSnippetEdit` a specified snippets file?

### ISSUE THREAD

**Issue by cometsong** [Shougo/neosnippet.vim#338]
Related to previous issue [add an option for `:NeoSnippetEdit` ](https://github.com/Shougo/neosnippet.vim/issues/33)

Is it possible to `:NeoSnippetEdit` a specific snippets file to edit when calling this function, instead of using the plugin's default?  (There are several snippet files existing.)

When I type `:NeoSnippetEdit -runtime -split -vertical` in a `.vim` file for example, it opens a file in your plugin's snippet dir, in a vim subdir, (`neosnippet-snippets/neosnippets/vim/vim.snip`), where only a`vital.snip` exists.  

I'd like to know how to edit the pre-existing user-defined snippet file in my own `g:neosnippet#snippets_director` (`~/.vim/bundle/vim-snippets/snippets/vim.snip`), or one of the other `vim*.snip` in your plugin's snippets dir. 

For reference: 
my .vimrc snippet settings:
```
"---- snippets ---- 
" Plugin key-mappings.
call MapKeys('ni', '<C-s>', '<Plug>(neosnippet_expand_or_jump)') 
call MapKeys('x', '<C-s>', '<Plug>(neosnippet_expand_target)') 

" SuperTab like snippets behavior.
imap <expr><TAB>
 \ pumvisible() ? "\<C-n>" :
 \ neosnippet#expandable_or_jumpable() ?
 \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

let g:neosnippet#enable_snipmate_compatibility = 1
let g:snippets_dir = '~/.vim/bundle/vim-snippets/snippets'

let g:neosnippet#snippets_directory = '~/.vim/snippets,'

"call MapKeys('ni', 'sns', '<C-c>:NeoSnippetSource ') 
call MapKeys('ni', 'sn', '<C-c>:NeoSnippetEdit -runtime -split -vertical<CR>') 

let g:neosnippet#scope_aliases = {}
let g:neosnippet#scope_aliases['python'] = 'python,django'
```
FYI, some of this is from your examples. 
Plus, the `MapKeys` function calls noremap for different mode keys.

Thanks!

**Comment by Shougo** [comment]
I don't want to add the feature.
But the Pull request is wellcome.

**Comment by cometsong** [comment]
Makes sense this is a feature request. 

Is there some other method to open a specific snippets file?
Other than knowing myself what the plugin paths are. 

Thanks for your wonderful work on these wonderful plugins @Shougo!

**Comment by Shougo** [comment]
> Is there some other method to open a specific snippets file?

Nothing.  So, you can implement the feature.
The source code is `neosnippet#commands#_edit()`.
https://github.com/Shougo/neosnippet.vim/blob/master/autoload/neosnippet/commands.vim#L44
I have not much time and interest.

Mytodo list:

* denite.nvim development
* neosnippet tests
* dein.vim development
