### ISSUE TITLE
multiple snippets folders

### ISSUE THREAD

**Issue by rockneverdies55** [Shougo/neosnippet.vim#339]
Is it possible to define multiple folders for snippets. 

For example I installed honza's vim-snippets and added `let g:neosnippet#snippets_directory='~/.vim/bundle/vim-snippets/snippets'` into my init.vim to use them. However I also would like to have `arnauddri/vim-lodash-snippets` snippets added too. 

Is that supported thing?

**Comment by Shougo** [comment]
```
g:neosnippet#snippets_directory		*g:neosnippet#snippets_directory*
		This variable appoints a path to user-defined snippet files.
		You can set multiple values in comma-separated string or list.
		Non existing directories are ignored.
```
