### ISSUE TITLE
NeoSnippet not initializing with newer Vim version (KaoriYa 1655)

### ISSUE THREAD

**Issue by yasen-atanasov** [Shougo/neosnippet.vim#340]
I've upgraded from KaoriYa Vim 7.4 patch 1490 to 1655. With 1655 I get the following errors:

1. On opening a file containing snippets:
![screenshot1](https://i.imgur.com/64VDWta.png)

2. On trying to expand a snippet:
![screenshot2](https://i.imgur.com/vqu957T.png)

I've temporarily downgraded to 1490 where neosnippet continues to work OK.

Let me know if there's anything else I can help with.

**Comment by Shougo** [comment]
OH, Vim's `string()` behavior is changed...
I will fix...

**Comment by Shougo** [comment]
Fixed.

**Comment by vialrogo** [comment]
Hi everyone,
I have the same issue. I'm using vim 7.4.1689-1 (archlinux version), and I have the last neosnippet update (using Neobundle). If I delete the ~/.cache/neosnippet folder, the error disappear, but after the first vim use, the error comes back. The permissions of the folder are fine. Somebody know what happens? Some information that I can provide?
Thanks

**Comment by Shougo** [comment]
@vialrogo I cannot reproduce it.
Please upload your neosnippet version by `git log`.

**Comment by vialrogo** [comment]
commit ce3c3d209c38a6d87bbf1408d293e179f95e7bb8
Author: Shougo Matsushita <Shougo.Matsu@gmail.com>
Date:   Wed Mar 30 07:20:16 2016 +0900

    Fix #340 cache error

**Comment by Shougo** [comment]
@vialrogo OK.  I want to reproduce it.
Please create minimal .vimrc less than 50 lines without the plugin manager and reproduce ways from Vim starting.

**Comment by vialrogo** [comment]
Now I can't reproduce, the error disappeared. I think that it was and update error. Please, sorry my mistake.
