### ISSUE TITLE
Edit file without file extension got "E713: Cannot use empty key for Dictionary"

### ISSUE THREAD

**Issue by wadegit** [Shougo/neosnippet.vim#341]
I found when I edit some files that has no file extension, like README, press "Tab" will trigger the following error:

Error detected while processing function neosnippet#expandable..neosnippet#get_snippets:
line    5:
E713: Cannot use empty key for Dictionary

However, when I changed its name to README.txt, the problem gone. 

Please help to check this issue since some common files has no file extension by default in Linux

Thanks,

**Comment by Shougo** [comment]
I think it is bug.
But I cannot reproduce it.
Please create minimal .vimrc and the reproduce ways from Vim starting.

My minimal .vimrc

```
set nocompatible

set runtimepath+=~/work/neosnippet.vim/
set runtimepath+=~/work/neosnippet-snippets/
set runtimepath+=~/work/neocomplete.vim/
let g:neocomplete#enable_at_startup = 1
imap <silent><C-l>    <Plug>(neosnippet_jump_or_expand)
```
