### ISSUE TITLE
newbie looking for neosnippet format explanation

### ISSUE THREAD

**Issue by nscott32** [Shougo/neosnippet.vim#342]
Hello,
I'm new to neosnippet and I'd like to understand how the snippet format for neosnippet work.
I haven't found any information about it, I'm familiar with ultinips format yet, I have read the snippets that come with neosnippet-snippets but I don't know what are options like head, alias.
Thank you for your understanding.

**Comment by Shougo** [comment]
`:help neosnippet-snippet-syntax`
