### ISSUE TITLE
Use neosnippet with vim-go

### ISSUE THREAD

**Issue by jsfaint** [Shougo/neosnippet.vim#343]
Recently I meet this issue when edit golang file with [vim-go](https://github.com/fatih/vim-go)
![vim](https://cloud.githubusercontent.com/assets/571829/15309385/315db6b6-1c19-11e6-88cc-8f281dd37d23.png)

This issue can be reproduced by the following step.
1. Expand any snippet
2. Save the file

Sorry I'm not sure it's issue in vim-go or neosnippet. But I tried ultisnips, there is no this issue.
Thanks

**Comment by Shougo** [comment]
Fixed.

**Comment by jsfaint** [comment]
Thanks :smile:
