### ISSUE TITLE
 Why is the default text deleted when hitting escape?

### ISSUE THREAD

**Issue by svermeulen** [Shougo/neosnippet.vim#344]
Repro steps:
- Expand snippet that contains default values
- Hit tab until you are at a default value
- Hit escape
- Default value is deleted.

I was able to fix this by removing the line `snoremap <ESC>    <BS><ESC>` from `mappings.vim`.

This seems to be intentional, so I'm wondering if I am doing something wrong?

Here's the snippet I'm using.  I'm hitting escape when it gets to `void`.

```
snippet method
alias me
    ${2:void} ${1:#:Method}()
    {${3}
    }

```

**Comment by Shougo** [comment]
OK.
