### ISSUE TITLE
Conceal and json

### ISSUE THREAD

**Issue by nemanjan00** [Shougo/neosnippet.vim#346]
Hello, 
I have a problem... 
When ``conceallevel`` is set to 2, I do not see quotes in **json** files...
This is my config: 
[https://github.com/nemanjan00/vim/blob/master/vimrc](https://github.com/nemanjan00/vim/blob/master/vimrc)
I would debug it, but, to be honest, I have no idea how...
Thank you

**Comment by Shougo** [comment]
Hm.  It is feature.  You can change the value...
