### ISSUE TITLE
Weird char at the EOL

### ISSUE THREAD

**Issue by gunar** [Shougo/neosnippet.vim#347]
Whenever I use a snippet (e.g. `req` from `neosnippet-snippets`/`javascript`) I get a weird char at the end of line: ``<`0`>``. I'm guessing this is VIM's representation of the null char.

Node.js won't execute files with those extra chars. Also, they appear on github's diff.

Is there a way to get rid of that?

Thank you so much!

> I'm using NeoVim, btw.

**Comment by gunar** [comment]
This is the definition:
```vim
snippet req
options word
  const ${1:#:name:} = require('${2:#:required}')
```

I just noticed that it doesn't add that weird char if I `ctrl+k` (move to next field) all the way to the end -- i.e. one `ctrl+k` for *name*, another for *required*, and yet another one to end the snippet.

**Comment by Shougo** [comment]
```
Q: I want to delete markers when InsertLeave event.

A: You can use |:NeoSnippetClearMarkers| command. >
	autocmd InsertLeave * NeoSnippetClearMarkers

```

**Comment by gunar** [comment]
You're the best. Thank you!
