### ISSUE TITLE
インサートモードにおけるCtrl+oの挙動について

### ISSUE THREAD

**Issue by Watchman3go** [Shougo/neosnippet.vim#348]
1週間ほど前からこのプラグインを利用させていただいています。
しかし、こちらのプラグインを利用することでインサートモード時のCtrl+o(一度だけノーマルモードのコマンドを入力できる)の挙動に不備を確認いたしました。
詳細に申し上げますと、インサートモード時にCtrl+oを入力、ノーマルモードでコマンドを実行後に再びインサートモードに遷移しません。
私の設定では、Ctrl+oにキーマップは設定しておらず、neosnippet.vimをロードせずに起動することでこの不備は確認されません。
また、コミットを辿らせていただいたところ以下の変更以降表題の挙動が確認されました。
cfc99eedb5caf3d6baf867db5220a891b4686699

私が利用しているプラグインとの衝突も考えられますが確認のほどよろしくお願いします。

**Comment by Shougo** [comment]
こちらでは再現しません。
再現するための最小構成を .vimrc 50 行以内で教えてください。
おそらくですが、InsertLeave 時に clear marker するような設定をしているのではないですか？
<C-o> 実行時に Insert を抜けるので、それと衝突するのです。

**Comment by Shougo** [comment]
一応この問題への対応はしました。

**Comment by Watchman3go** [comment]
ありがとうございました。
