### ISSUE TITLE
A snippet with options head expands when used in a placeholder

### ISSUE THREAD

**Issue by pfmoore** [Shougo/neosnippet.vim#349]
As an example, define a snippet like this:

```
snippet     def
abbr        def function(...): ...
options     head
	def ${1:#:name}(${2}):
		${0:pass}
```

(From neosnippet-snippets for Python) Now define ```<C-k>``` to expand or jump, as in the manual.

```
imap <C-k> <Plug>(neosnippet_expand_or_jump)
```

Now enter the following in a new Python file (i.e, where the snippet is active): ```def<C-k>```. The snippet expands, leaving you on the text "name". Now type ```def<C-k>``` again, as if you were trying to define a function called ```def```, and now wanted to jump to the arguments. What actually happens is that the ```def``` snippet is expanded again.

(The actual case where this hit me is trying to define a function called ```main()```, as ```main``` is used in neosnippet-snippets as an alias for the "ifmain" snippet (which has option head set)).

**Comment by Shougo** [comment]
Fixed.
