### ISSUE TITLE
Expansion causes extra indenting of snippet

### ISSUE THREAD

**Issue by subshad** [Shougo/neosnippet.vim#350]
Hi, thanks for releasing this. 

I'm seeing some odd behaviour, which I think is related to the snippet being entirely wrapped in parentheses. I've replicated it with the iife snippet in the neosnippet-snippets repo, as well as with the custom one below. Is there somewhere I should begin looking?
 
```
snippet describe
abbr    desc
options word
  describe(${1:description}, () => {
    ${0:TARGET}
  })
```

**Comment by Shougo** [comment]
```
If you use hard-tab for indentation inside a snippet file, neosnippet will use
'shiftwidth' instead of Vim indent plugin. This feature is useful while some
languages' indent files do not work very well (e.g.: PHP, Python).
>
	snippet if
	  if (${1:/* condition */}) {
	      ${2:// code...}
	  }
<
```

Please read neosnippet documentation.

**Comment by subshad** [comment]
I saw that but didn't understand the shiftwidth implication. Using hard-tabs fixes my problem, thank you :smile:
