### ISSUE TITLE
Wrong behavior when expanding snippet

### ISSUE THREAD

**Issue by hgiesel** [Shougo/neosnippet.vim#351]
I have a snippet like this:

```vimscript
snippet (
abbr Parenthesis
options word
>       (${1})${0}
```

And I have in my vimrc:

```vimscript
imap <C-j> <Plug>(neosnippet_expand_or_jump)
```

Then when i type e.g. `foobar()` like this: `foobar(<c-j><c-j>` I will get this: `foobar())`
Basically there will be two expands instead of one expand and then one jump.

I feel like <Plug>(neosnippet_expand_or_jump) basically just looks if there is a keyword right before it, but I think it should disable an expand if there just was one.

**Comment by Shougo** [comment]
I have reproduced it.  It is bug.
