### ISSUE TITLE
Cannot use without Shougo/neosnippet-snippets

### ISSUE THREAD

**Issue by CrashyBang** [Shougo/neosnippet.vim#352]
Hey,

Ideally I would like to use neosnippet without [neosnippet-snippets](https://github.com/Shougo/neosnippet-snippets).

I tried defining my own snippets directory: 
`let g:neosnippet#snippets_directory='~/.config/nvim/snippets'` but if I uninstall neosnippet-snippets it fails.

I also tried disabling it:
```vim
let g:neosnippet#disable_runtime_snippets = {
        \   '_' : 1,
        \ }
```

But this disables it altogether.

Any ideas?
Cheers.

**Comment by Shougo** [comment]
Please upload the minimal vimrc and reproduce ways.
I will test it.

>  let g:neosnippet#snippets_directory='~/.config/nvim/snippets' but if I uninstall neosnippet-snippets it fails.

What is the `fails` means?
Please describe it.

**Comment by CrashyBang** [comment]
Hey @Shougo,

Looks like it may be another plugin although I was sure I was able to reproduce before, sorry :(.

Cheers.

**Comment by Shougo** [comment]
OK.

**Comment by CrashyBang** [comment]
Hey @Shougo,

As a side note I am always receiving this error:

```
[neosnippet] neosnippet default snippets cannot be loaded.                                                                                            
[neosnippet] You must install neosnippet-snippets or disable runtime snippets.
```

Even when this line is enabled: `let g:neosnippet#snippets_directory='~/.config/nvim/snippets'`

Am I able to prevent this?

**Comment by Shougo** [comment]
```vim
let g:neosnippet#disable_runtime_snippets = {
        \   '_' : 1,
        \ }
```

is needed.

**Comment by CrashyBang** [comment]
Don't know what I was doing before but sorted now, sorry to waste your time.

Cheers.
