### ISSUE TITLE
strange snippet expansion

### ISSUE THREAD

**Issue by habamax** [Shougo/neosnippet.vim#354]
I have a snippet like:

     snippet options
         ---
         title: "${1}"
         subtitle: "${2}"
         subtitle2: "${3}"
         author: Максим Ким
         titlepage: yes
         lang: ru
         toc: yes
         documentclass: article
         logoleft: ${4:logo-semanta-black.png}
         logoleft-scale: 0.21
         logoright: ${5:logo-adastra.png}
         logoright-scale: 0.11
         ...
     
         ${0}

made for a pandoc filetype.

After expansion I get the following result:

     ---
     title: ""
     subtitle: "<`2`>"
     subtitle2: "<`3`>"
     author: Максим Ким
     titlepage: yes
     lang: ru
     toc: yes
     documentclass: article
     			   logoleft: <`4:logo-semanta-black.png`>
     						logoleft-scale: 0.21
     								 logoright: <`5:logo-adastra.png`>
     									   logoright-scale: 0.11
     										  ...
     
     											 <`0`>

If I remove documentclass line I get correct expansion:

    ---
    title: ""
    subtitle: "<`2`>"
    subtitle2: "<`3`>"
    author: Максим Ким
    titlepage: yes
    lang: ru
    toc: yes
    logoleft: <`4:logo-semanta-black.png`>
    logoleft-scale: 0.21
    logoright: <`5:logo-adastra.png`>
    logoright-scale: 0.11
    ...
    
    <`0`>

Windows 10, vim 8

**Comment by Shougo** [comment]
You should use tab characters instead of spaces.
