### ISSUE TITLE
expand slow with vim-orgmode plugin

### ISSUE THREAD

**Issue by whisper404** [Shougo/neosnippet.vim#356]
# Problems summary

When I edit org files with vim-orgmode plugin, neosnippet expand is very slow. It cost about 1-2 seconds to expand text.  Also, expand is slower than vim.
## Environment Information
- OS:macOS 10.12.1
- Vim version:NVIM v0.1.6-279-gf96dfae
## Provide a minimal .vimrc with less than 50 lines (Required!)

``` vim
" Your minimal .vimrc
let s:cache_dir = expand('~/.cache/')
execute 'set runtimepath^=' . s:cache_dir . '/dein/repos/github.com/Shougo/dein.vim'
call dein#begin(s:cache_dir . '/dein')
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/neosnippet-snippets')
call dein#add('Shougo/neosnippet.vim', {
            \ 'hook_add': "
            \ imap <C-k> <Plug>(neosnippet_jump_or_expand)"
            \ })
call dein#add('Shougo/deoplete.nvim' , {
            \ 'hook_add': "let g:deoplete#enable_at_startup = 1"
            \ })
call dein#add('jceb/vim-orgmode')
call dein#end()
filetype plugin indent on

```
## The reproduce ways from Vim starting (Required!)
1. Open org file in vim.
2. Input date
3. Press Ctrl-K to expand text.

**Comment by Shougo** [comment]
I will check it later.
But vim-orgmode uses if_python as folding/indent expr.
It is slow in neovim.

**Comment by Shougo** [comment]
>When I edit org files with vim-orgmode plugin, neosnippet expand is very slow. It cost about 1-2 seconds to expand text. Also, expand is slower than vim.

Hm.  To edit org files are needed.
Please add it in the reproduce ways.

**Comment by whisper404** [comment]
> Note: You can reproduce the behavior with empty org file?

In empty org file neosnippet is fast. This issue appeared when I edit 1000 lines file.

**Comment by Shougo** [comment]
Please upload the 1000 lines org file.
I must test it using the file.

**Comment by whisper404** [comment]
I made a new org file. Please check it.
[test.org.zip](https://github.com/Shougo/neosnippet.vim/files/557691/test.org.zip)

**Comment by Shougo** [comment]
Reproduced.  And it is not neosnippet problem.
It is because foldmethod=expr is too slow especially in huge buffer.

The latest neovim fix the problem in insert mode only.
But neosnippet modify the buffer in normal mode.
So it is slow.  I cannot fix the problem.

**Comment by justinmk** [comment]
@whisper404 what "Build type" is reported by `:version`? Nvim should not be any slower than vim for foldmethod=expr.

**Comment by whisper404** [comment]
@justinmk Build type: Dev

**Comment by justinmk** [comment]
That may be why it is slower. Try an optimized build.

**Comment by Shougo** [comment]
> Also, expand is slower than vim.

I think it is because if_python implementation difference.

Vim: if_python is just dll call
neovim: if_python is MessagePackRPC

dll call is faster than MessagePackRPC
