### ISSUE TITLE
Trigger `enable_completed_snippet` only when pressing a certain key binding

### ISSUE THREAD

**Issue by svanharmelen** [Shougo/neosnippet.vim#357]
Is there any way to trigger `enable_completed_snippet` only when pressing a certain key binding? I find it very annoying that is always provides the dynamically generated snippet and would like to be able to call for it.

Say I am typing and I get a few autocomplete options from `deoplete.nvim` I press <C-n> a couple of times and then only when I type a specific keybinding I get the snippet. So if I don't use that specific keybinding I just use the autocomplete option as usual.

Would be really cool if I could use it like that, because having it always trigger is not making my life easier. Thanks!!

**Comment by Shougo** [comment]
I will implement the feature.

**Comment by svanharmelen** [comment]
@Shougo that would be awesome! Thanks!

**Comment by Shougo** [comment]
I have implemented it.

**Comment by svanharmelen** [comment]
@Shougo really a nice way how you implemented it now, and it works perfectly! Thanks!

One last question I do have is why it is now still required to set `call deoplete#custom#set('_', 'converters', ['converter_auto_paren'])`? Isn't it possible to enable/use these dynamic completions without `converter_auto_paren`?

Thanks...

**Comment by svanharmelen** [comment]
@Shougo but if I use that, the completions generated by `enable_completed_snippet` are not triggered. In order to make that work, I need to add the `converter_auto_paren` option (which I would rather not add)...

**Comment by Shougo** [comment]
It is another issue.
Please create the new issue with minimal configuration and the examples.
I will check it.

**Comment by svanharmelen** [comment]
Will do... Thanks.

**Comment by Shougo** [comment]
neosnippet implements the auto detection parentheses feature.
It should be worked.
