### ISSUE TITLE
The `enable_completed_snippet` feature requires `converter_auto_paren` to be set

### ISSUE THREAD

**Issue by svanharmelen** [Shougo/neosnippet.vim#358]
When using this `init.vim` is does not trigger the dynamically created prototype snippets:

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-go', { 'do': 'make' }
Plug 'shougo/neosnippet'
Plug 'fatih/vim-go'
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:neosnippet#enable_completed_snippet = 1
```

But when adding the `converter_auto_paren`, it works as expected:

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-go', { 'do': 'make' }
Plug 'shougo/neosnippet'
Plug 'fatih/vim-go'
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:neosnippet#enable_completed_snippet = 1

call deoplete#custom#set('_', 'converters', ['converter_auto_paren'])
```

Isn't it possible to make it work without the need for `converter_auto_paren`?

**Comment by Shougo** [comment]
Please create the reproduce way.

I have not ESP skill.

**Comment by svanharmelen** [comment]
To reproduce add `imap <expr><CR> neosnippet#expandable() ? "\<Plug>(neosnippet_expand)" : "\<CR>"` to the `init.vim` example and do:

1. Open a Go source file
2. Type `fmt.`
3. From the completions select `fmt.Errorf` and press `<CR>`

Without `converter_auto_paren`:
![bad](https://cloud.githubusercontent.com/assets/4171547/20004710/33f6dabe-a28e-11e6-8ed5-cb85e4fbf583.gif)

With `converter_auto_paren`:
![good](https://cloud.githubusercontent.com/assets/4171547/20004720/39ce07e6-a28e-11e6-8187-afdcb8c9aa55.gif)

**Comment by Shougo** [comment]
deoplete-go does not work in my environment.
It prints `gocode panicked` error.
I cannot reproduce it...

**Comment by svanharmelen** [comment]
Do you have a `$GOPATH` set and have the source Go file in `$GOPATH/src/`?

Also are you running the latest version of gocode? Of you have `vim-go` installed, just do `:GoUpdateBinaries` and/or `:GoInstallBinaries` if needed...

**Comment by svanharmelen** [comment]
@Shougo if after updating it still doesn't work, you can also try `gocode close` and then try again...

**Comment by Shougo** [comment]
It worked.  Thanks.
I have reproduced the problem...

**Comment by svanharmelen** [comment]
Cool, hope you can find a solution. Thx!

**Comment by Shougo** [comment]
Fixed.

**Comment by svanharmelen** [comment]
Yes! Works great, thank you very much! 🎉
