### ISSUE TITLE
missing mode in docs for <Plug>(neosnippet_expand_or_jump)

### ISSUE THREAD

**Issue by nhooyr** [Shougo/neosnippet.vim#362]
`<Plug>(neosnippet_expand_or_jump)` is an insert mode mapping but that is not reflected in the docs.

https://github.com/Shougo/neosnippet.vim/blob/9132237f3cf445911830c546782d81b1e0504ded/doc/neosnippet.txt#L277

It should be `i_<Plug>(neosnippet_expand_or_jump)`

It's also missing for `<Plug>(neosnippet_jump_or_expand)`.

**Comment by Shougo** [comment]
Fixed.
