### ISSUE TITLE
incorrect parsing with enable_completed_snippet and go

### ISSUE THREAD

**Issue by nhooyr** [Shougo/neosnippet.vim#363]
In go, functions can return multiple values. It looks like:

```go
func Executable() (string, error) {
	return executable()
}
```

Unfortunately, neosnippet's enable_completed_snippet feature is parsing these as arguments so if you try to use that feature when completing a function with multiple return values, you get something like ``os.Executable(string, <`2:#:error`>)<`3`>``.

**Comment by nhooyr** [comment]
Whereas if you do the same on a function like `time.Now` which returns a single value, it expands to `time.Now()`. So, the above should expand to `os.Executable()`

**Comment by Shougo** [comment]
Unfortunately, it is feature.

neosnippet must parse the documentation pattern.

```vim
wait()    wait(long, int)
```

It should be expanded to `wait(long, int)`

**Comment by Shougo** [comment]
Fixed.
