### ISSUE TITLE
differences from neosnippet 

### ISSUE THREAD

**Issue by nhooyr** [Shougo/neosnippet.vim#365]
What makes this plugin different from ultisnips? They both seem really similar.

**Comment by Shougo** [comment]
Multiple post:
https://github.com/SirVer/ultisnips/issues/807

Do you think both seem similar?
No.

neosnippet is Vim script based plugin.
UltiSnips is if_python based plugin.

neosnippet uses snipMate based snippet syntax.
UltiSnips uses the original syntax.

UltiSnips users can embed Python code in the snippet syntax.

neosnippet uses the jump marker.  It cannot support backward jump.
UltiSnips does not use the marker.  But it must detect the buffer change.
It will be slower.

**Comment by nhooyr** [comment]
I wanted both perspectives is all :)

thanks!

**Comment by Shougo** [comment]
UltiSnips is slow in neovim.
Because, neovim if_python implementation is slow.

Note:  I will rewrite neosnippet in the future.
https://github.com/Shougo/deoppet.nvim

**Comment by lfilho** [comment]
Ooh, I came here research about which snipet engine to use with `nvim` (i've been using snipmate so far). Nice. So I guess I should wait for `deoppet`? Or does neosnippet works well with `nvim`?

Also, if you don't mind answering some more questions:
1) Why don't you use the snippets at https://github.com/honza/vim-snippets since they also have the snipmate format?
2) When do you think `deoppet` will be usable?

THANKS again for your great effort with some many nice plugins! You rock!

**Comment by Shougo** [comment]
> Or does neosnippet works well with nvim?

neosnippet works well with nvim.

> So I guess I should wait for deoppet?

It takes more time.  I am busy to fix the plugin bugs.

> When do you think deoppet will be usable?

I think it is in 2018.

> Why don't you use the snippets at https://github.com/honza/vim-snippets since they also have the snipmate format?

Because I like neosnippet-snippets.

**Comment by svanharmelen** [comment]
I just noticed this thread and the link to deoppet. Can you share any updates on when you think deoppet will be stable and can be used? Thanks!

**Comment by Shougo** [comment]
> I just noticed this thread and the link to deoppet. Can you share any updates on when you think deoppet will be stable and can be used? Thanks!

It is in 2019 someday.  Because In 2018 is defx.nvim development turn.

**Comment by Shougo** [comment]
>  I think it is in 2018.

The plan is changed...

And deoppet.nvim is neovim only plugin.

**Comment by svanharmelen** [comment]
Check! And I'm using neovim, so that's all good 👍
