### ISSUE TITLE
Emphasize use of recursive mappings in examples/documentation

### ISSUE THREAD

**Issue by jabocg** [Shougo/neosnippet.vim#366]
I just went through a struggle trying to get the following mappings to work:

```vim
inoremap <expr><C-SPACE> neosnippet#expandable() ? "\<Plug>(neosnippet_expand)" : "\<C-X><C-O>"
inoremap <expr><C-L> "\<Plug>(neosnippet_jump)"
```

only to realize that you **HAVE** to use recursive mappings

```vim
imap <expr><C-SPACE> neosnippet#expandable() ? "\<Plug>(neosnippet_expand)" : "\<C-X><C-O>"
imap <expr><C-L> "\<Plug>(neosnippet_jump)"
```

It would be nice(read: lowest priority) if this could be emphasized in the examples and documentation.

**Comment by Shougo** [comment]
Do you know `<Plug>` mapping feature?
I have thought it is well known feature.
