### ISSUE TITLE
enable_completed_snippet does not work properly with nested snippets

### ISSUE THREAD

**Issue by nhooyr** [Shougo/neosnippet.vim#367]
Open `|` is the cursor:

```go
package main

func something(bar func(i int), foo int) {}

func main() {
    |
}
```

https://asciinema.org/a/ekj3c9n8lrvgnug4fq918mkds

See how after the return argument, it jumps straight to the end of the function call to `something()` even though it should have jumped to the body of the function argument?

**Comment by nhooyr** [comment]
I'll post the snippets I used in a minute.

**Comment by Shougo** [comment]
It is the feature currently.
Because, neosnippet uses the marker.
I think the next snippet plugin fixes the problem.
