### ISSUE TITLE
enable_completed_snippet select commas

### ISSUE THREAD

**Issue by nhooyr** [Shougo/neosnippet.vim#368]
Right now, enable_completed_snippet does not select commas. So this happens:

https://asciinema.org/a/8gt512mchmo2riu2ga7jmmwq0

See how when I exit normal mode and move down, the commas are left over? That's because they weren't part of the selection of the snippet.

This would be a breaking change, so it should be put behind an option.

**Comment by Shougo** [comment]
Implemented.
I don't want to add the option.
