### ISSUE TITLE
How to COMPLETELY delete an existing snippet?

### ISSUE THREAD

**Issue by e-kwsm** [Shougo/neosnippet.vim#369]
`delete` is implemented but intended for redefinition of snippets.
For example even if I `delete path` in my custom `_.snip`, snippet `path` is STILL active so I cannot use literal `path`while using other snippets.

The following code does not work—`path` is not expanded but unable to jump to the next marker
```
delete path
snippet path
    path
```

How to completely delete and avoid expanding an existing snippet?

cf. #276

**Comment by e-kwsm** [comment]
Actually appending white space (e.g. `path␣^k`) avoids to expand the snippet, but often requires to remove the spaces afterward, or causing bug.

**Comment by Shougo** [comment]
Yes, this is feature currently.
`delete` removes the current snippet.  But it does not remove the other default snippets.

To fix it is hard.
