### ISSUE TITLE
Improper indentation

### ISSUE THREAD

**Issue by pik4ez** [Shougo/neosnippet.vim#370]
I've got a snippet:
```
snippet fn
abbr protected function () { ... }
    public function ${1}(${2}) {
        ${0:TARGET}
    }
```

It expands like this:
```
public function (<`2`>) {
<`0:TARGET`>
}
```

Consider there's no four spaces before <`0:TARGET`>. Spaces do not appear even if I modify source and add some extra spaces before corresponding line.

Converting a placeholder to optional, by the way, makes gone spaces to reappear:
```
snippet fn
abbr protected function () { ... }
    public function ${1}(${2:#:options}) {
        ${0:TARGET}
    }
```

Expanded snippet:
```
public function (<`2:#:options`>) {
    <`0:TARGET`>
}
```

**Comment by ujihisa** [comment]
https://github.com/Shougo/neosnippet.vim/blob/master/doc/neosnippet.txt#L699

**Comment by Shougo** [comment]
Please read L714 in neosnippet documentation.
