### ISSUE TITLE
Not loading code igniter snippets from "Honza" folder

### ISSUE THREAD

**Issue by Msouza91** [Shougo/neosnippet.vim#373]
I'm using compatibility mode and pointed to the honza snippets folder as instructed on README and it's not loading the CI snippets on php files!

**Comment by Shougo** [comment]
I think CI snippets is this.
https://github.com/honza/vim-snippets/blob/ca7b3e6e349908ae93bca885f3f9bbd4f6cf9fb6/snippets/codeigniter.snippets

You must set the filetype to `php.codeigniter`

**Comment by Msouza91** [comment]
Doing this made the base php snippets not work either...

**Comment by Msouza91** [comment]
My Mistake! Thanks for the help!
