### ISSUE TITLE
Weird snippet behaviour

### ISSUE THREAD

**Issue by olimorris** [Shougo/neosnippet.vim#379]
Trawling through the documents I can't seem to work out why the below snippet doesn't work as desired.

My issues are:

1.  The first placeholder doesn't work, presumably because of my use of the '\' character. I've tried '\\' and it gives the same result.
2.  The indentation for the method (public function) is non existant.

```
snippet test
    <?php

    namespace Tests\${1:Feature};
    
    use Tests\Testcase;
    use Illuminate\Foundation\Testing\WithoutMiddleware;
    use Illuminate\Foundation\Testing\DatabaseMigrations;
    use Illuminate\Foundation\Testing\DatabaseTransactions;

    class ${2}Test extends TestCase
    {
        ${3:use DatabaseMigrations, DatabaseTransactions;}

        /** @test */
        public function ${4}()
        {
            ${0}
        }
    }
```

Other than this snippet, everything works perfectly. I've shifted from SnipMate to this last night and am using the latest version, in MacVim 8.0.502 (129) and Vim 8.0,

**Comment by Shougo** [comment]
> The first placeholder doesn't work, presumably because of my use of the '' character. I've tried '\' and it gives the same result.

It must be `    namespace Tests\\${1:Feature};`.
You must escape `\` character.

> The indentation for the method (public function) is non existant.

> Trawling through the documents I can't seem to work out why the below snippet doesn't work as desired.

```
If you use hard-tab for indentation inside a snippet file, neosnippet will use
'shiftwidth' instead of Vim indent plugin. This feature is useful while some
languages' indent files do not work very well (e.g.: PHP, Python).
>
	snippet if
	  if (${1:/* condition */}) {
	      ${2:// code...}
	  }
<

```

Really?  Please read the documentation.

**Comment by olimorris** [comment]
> It must be namespace Tests\\${1:Feature};. You must escape \ character.

Unfortunately this makes no difference. I tried to explain in my first post that I escaped with `\\` (apologies it was parsed out by Markdown originally) and it made no difference.

> Really? Please read the documentation.

The documentation is as clear as mud unfortunately. You have had a number of issues in the past with people asking about indentation. What is it telling me to do, exactly? Use shiftwidth's? I am using shiftwidth's. The relevant extract from my `.vimrc`:

```
    set tabstop=4
    set softtabstop=4 
    set shiftwidth=4
    set expandtab
    set shiftround
```

**Comment by Shougo** [comment]
@olimorris Please use hard tab instead in your PHP snippets.

**Comment by Shougo** [comment]
```
snippet test
	<?php
	
	namespace Tests\\${1:Feature};
	
	use Tests\Testcase;
	use Illuminate\Foundation\Testing\WithoutMiddleware;
	use Illuminate\Foundation\Testing\DatabaseMigrations;
	use Illuminate\Foundation\Testing\DatabaseTransactions;
	
	class ${2}Test extends TestCase
	{
		${3:use DatabaseMigrations, DatabaseTransactions;}
		
		/** @test */
		public function ${4}()
		{
			${0}
		}
	}
```
