### ISSUE TITLE
snipmate compatibility not working in windows

### ISSUE THREAD

**Issue by cristobaltapia** [Shougo/neosnippet.vim#381]
I have activated the snipmate compatibility to add the Honza's snippets as described in the configuration instructions:
```
" Enable snipMate compatibility feature.
let g:neosnippet#enable_snipmate_compatibility = 1

" Tell Neosnippet about the other snippets
let g:neosnippet#snippets_directory=[
            \'~/.vim/plugged/vim-snippets/snippets',
            \'~/.vim/plugged/MySnippets',
            \]
```

I can check that this is correctly set by doing 
```
:echo g:neosnippet#enable_snipmate_compatibility
1
```

and
```
:echo g:neosnippet#snippets_directory
['H:/.vim/plugged/vim-snippets/snippets', 'H:/.vim/plugged/MySnippets']
```

When I am editing a file (e.g. tex file) only the neosnippet-snippets and the snippets defined in MySnippets folder are available, but not the ones from Honza.

**Comment by Shougo** [comment]
I cannot reproduce the problem.

Please check `neosnippet#helpers#get_snippets_directory()` is correct.

And you can check the loaded snippets by `neosnippet#helpers#get_snippets()`.

And you should check the buffer is really `tex` filetype.

**Comment by Shougo** [comment]
I get it.  Your configuration is wrong.

It must be:

```vim
" Tell Neosnippet about the other snippets
let g:neosnippet#snippets_directory=[
            \'~/.vim/plugged/vim-snippets',
            \'~/.vim/plugged/MySnippets',
            \]
```

neosnippet use snippets directory automatically.

**Comment by Shougo** [comment]
You must need to set runtimepath.

```vim
set rtp+=~/.vim/plugged/vim-snippets
```

**Comment by cristobaltapia** [comment]
Thanks for the answers Shougo. I think that I only have the problem with ``*tex`` files, since the python snippets work correctly. So there is probably something else wrong with my ``vimrc`` (maybe vim-latex).

**Comment by Shougo** [comment]
I get it.
The trigger is converted.

For example, `ms mathscr` is `ms_matchstr`.

**Comment by cristobaltapia** [comment]
Yes, that seems to be happening!

**Comment by Shougo** [comment]
> So is this a bug?

No.  It is the feature for compatibility.

Please read this.

https://github.com/garbas/vim-snipmate/blob/master/doc/SnipMate.txt#L250

snipmate has multisnip feature.
neosnippet does not support it.
The trigger must be unique in neosnippet.
So neosnippet converts multisnip trigger like "ms mathscr" to ""ms_matchstr.

**Comment by Shougo** [comment]
I recommend for you to use completion plugin like neocomplete or deoplete.
