### ISSUE TITLE
Using back tics in markdown snippets for displaying inline code is escaped 

### ISSUE THREAD

**Issue by wikimatze** [Shougo/neosnippet.vim#384]
## Problems summary

Using a snippet for markdown files to include inline code examples with back tics are escaped with deoplete in completion.

## Expected

The surroundings for code snippets are inserted in the correct way, like
<pre>
``
</pre>

## Environment Information (Required!)

- deoplete.nvim (https://github.com/Shougo/deoplete.nvim/commit/bda6d16700d8d728ebd5d422d4936a5977c40273)
- Ubuntu 14.04 trusty
- neovim version:

<pre>
NVIM v0.2.0-1420-g19646a29
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/tmp/neovim/build/config -I/tmp/neovim/src -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/usr/include -I/tmp/neovim/build/src/nvim/auto -I/tmp/neovim/build/include
Compiled by wm@wm

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
</pre>

- vim version:
<pre>
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 21 2017 14:41:45)
Included patches: 1-575
Compiled by wm@wm
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    -netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/i386-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -fstack-protector -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lnsl  -lselinux  -lncurses -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2   -L/usr/lib/python3.4/config-3.4m-i386-linux-gnu/ -lpython3.4m -lpthread -ldl -lutil -lm  -Wl,-R/home/wm/.rvm/rubies/ruby-2.4.1/lib -L/home/wm/.rvm/rubies/ruby-2.4.1/lib -lruby -lpthread -lgmp -ldl -lcrypt -lm
</pre>

## Provide a minimal init.vim

```

call plug#begin('~/.config/nvim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/neosnippet.vim', 'affc71b'

call plug#end()

let g:deoplete#enable_at_startup = 1

au! BufRead,BufNewFile *.m*down,*md,*.html.markdown.erb set filetype=markdown

" SuperTab like snippets behavior.
imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)"
\: pumvisible() ? "\<C-n>" : "\<TAB>"

" Tell Neosnippet about the other snippets
let g:neosnippet#snippets_directory='~/.config/nvim/snippets'
```

The content of `~/.config/nvim/snippets/markdown.snip`:

<pre>
snippet ic
  \`${1:}\`
</pre>

## The reproduce ways from neovim starting (Required!)

- Open a markdown file
- go into insert mode, type `ic` and then `<Tab>`
- result will be:
<pre>
\`\`
</pre>

- instead of expected:
<pre>
``
</pre>

**Comment by Shougo** [comment]
I cannot reproduce it.
I think your neosnippet is not the latest version.

**Comment by Shougo** [comment]
`Plug 'Shougo/neosnippet.vim', 'affc71b'`

Version locked!
Please use the latest version.

**Comment by Shougo** [comment]
Oh, I get it.
It is just completion menu.

**Comment by Shougo** [comment]
Fixed.

**Comment by wikimatze** [comment]
Yeah, I have thought that it must be escaped somewhere in the codebase - thanks for fixing it.
