### ISSUE TITLE
Indent with tab not working when use completion with tab.

### ISSUE THREAD

**Issue by andreepratama27** [Shougo/neosnippet.vim#389]
I've been using this package for code completion and everything works goes well. But when I use tab for indentation, tab doesn't work. How to solve this problem? Thanks.

**Comment by Shougo** [comment]
I don't understand your issue.
Please upload the examples.

**Comment by eljusto** [comment]
1. type if
2. select if-else in menu
3. press Enter.
Expected result: if () {} else {}
Actual result: if-else

**Comment by Shougo** [comment]
OK.  I get it.
If you want to expand the snippet trigger by `<Enter>`, please use the mapping.

```vim
	" Expand the snippet trigger by <CR>.
	imap <expr><CR>
	\ (pumvisible() && neosnippet#expandable_or_jumpable()) ?
	\ "\<Plug>(neosnippet_expand_or_jump)" : "\<CR>"
```

**Comment by eljusto** [comment]
I don't know Vimscript, but this code just inserts string '(pumvisible() && neosnippet#expandable_or_jumpable()) ? "\<Plug>(neosnippet_expand_or_jump)" :' when I press Enter

**Comment by Shougo** [comment]
@eljusto I think you have forgot `<expr>`.

**Comment by Shougo** [comment]
Please create the minimal vimrc if you think not wrong.

**Comment by eljusto** [comment]
Here is it. 
```if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/neocomplete.vim'
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/neosnippet-snippets'
call neobundle#end()

filetype plugin indent on

syntax on
" NeoComplete
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3

" Expand the snippet trigger by <CR>.
  imap <expr><CR>
        \ (pumvisible() && neosnippet#expandable_or_jumpable()) ?
        \ "\<Plug>(neosnippet_expand_or_jump)" : "\<CR>
```

**Comment by eljusto** [comment]
I have found that my issue was caused by tpope/vim-endwise extension.
For now autocomplete works by a bit strange. E.g., `iife` unfolds to 
```
(function(      ) {
'use strict';
        <`0:TARGET`>
})(<`2`>)
```

**Comment by Shougo** [comment]
OK.  vim-endwise overwrites `<CR>`.
So it will be broken.

**Comment by Shougo** [comment]
> For now autocomplete works by a bit strange

What is the strange?  I don't understand it.

**Comment by eljusto** [comment]
I thought that it will be placeholders and I could fill it and switch between with TAB key.

**Comment by Shougo** [comment]
> I thought that it will be placeholders and I could fill it and switch between with TAB key.

It depends on your `<TAB>` key mapping.
