### ISSUE TITLE
Changing placeholder text interferes with pasting

### ISSUE THREAD

**Issue by jeromedalbert** [Shougo/neosnippet.vim#396]
### Description

If you have neovim configured with `clipboard=unnamed`, and if you expand a snippet and replace a placeholder text `"abc"` with some other text, when you paste with `p`, the pasted text is `"abc"`, which is never what you want since `"abc"` is a placeholder text.

I don't know if it is default VIM behavior. But it would be nice if the default register used by `p` was not replaced (or restored when exiting the snippet). See steps to reproduce for more details.

### Files to reproduce

Minimal `vimrc`:
```vim
call plug#begin('~/.vim/plugged')
Plug 'Shougo/neosnippet.vim'
call plug#end()

set clipboard=unnamed

let g:neosnippet#disable_runtime_snippets = { '_' : 1 }
let g:neosnippet#snippets_directory='~/.vim/my-snippets'

imap <tab> <Plug>(neosnippet_expand_or_jump)
smap <tab> <Plug>(neosnippet_expand_or_jump)
xmap <tab> <Plug>(neosnippet_expand_target)
```

Minimal `~.vim/my-snippets/ruby.snippets` file:

```
snippet map
abbr map { |element| .. }
options word
  map { |${1:element}| ${0} }

```

### Steps to reproduce

1. Do `:set filetype=ruby`
2. Type some text, like `hello`
3. Copy the `hello` text with `yy`. Now `hello` is in the unnamed `"` register.
4. Go into insert mode on a new line and type `dogs.map`
5. Press the `<tab>` key. The snippet gets expanded, and your cursor is now in select mode on the `element` text.
6. Type `dog`
7. Press the `<tab>` key.
8. Press `<esc>`.
9. Paste with `p`.

### Actual behavior

The `element` text is pasted.

### Expected behavior

The `hello` text should be pasted.

### Notes

What is weird in my steps to reproduce is that  `:echo @"` displays `hello`, so the unnamed `"` register still contains `hello`. But typing `p` does not paste `hello`, it pastes `element. It looks like I am confused by what register `p` uses by default. I thought it used `"`. But if I do `:registers`, it looks like `p` is using `*`.

The issue disappears if you do `set clipboard=`, but I want to keep it set to `unnamed`, so that I can easily integrate with my OS clipboard. So I am looking for a workaround.

**Comment by Shougo** [comment]
This is Vim's feature.
I cannot fix it.

**Comment by jeromedalbert** [comment]
Mmmh, according to `:h primary-selection`:

> When the "unnamed" string is included in the 'clipboard' option, the unnamed
register is the same as the "* register.

But `:reg "` displays `hello`, and `:reg *` displays `element`. The documentation suggests it should be the same. Not sure if this is a (Neo)Vim bug or expected feature.

**Comment by Shougo** [comment]
snippet plugin use the select mode as the place holder selection.
But it changes unnamed register(`"`).
It is the feature.
