### ISSUE TITLE
Question: `class="$1"` snippet not working?

### ISSUE THREAD

**Issue by roxma** [Shougo/neosnippet.vim#399]
As per https://github.com/autozimu/LanguageClient-neovim/pull/121#issuecomment-326545360

minimal vimrc:

```vim
set nocompatible
syntax on
filetype plugin indent on
set encoding=utf-8 fileencodings=ucs-bom,utf-8,gbk,gb18030,latin1 termencoding=utf-8

call plug#begin(expand('<sfile>:h') . '/plugged/')
Plug 'Shougo/neosnippet'
Plug 'Shougo/neosnippet-snippets'
call plug#end()

set filetype=txt

imap <c-j>     <Plug>(neosnippet_expand_or_jump)
vmap <c-j>     <Plug>(neosnippet_expand_or_jump)
imap <silent> <c-u> <Plug>(neosnippet_expand_or_jump)

```

snippet file  `txt.snip`

```
snippet     class
abbr        class=""
  class="$1"
```

Behavior:
![neosnippet](https://user-images.githubusercontent.com/4538941/29966389-42a11914-8f44-11e7-9603-db1bd249256d.gif)

**Comment by roxma** [comment]
It works when I change `class="$1"` into `class="${1}"`

**Comment by Shougo** [comment]
It is feature.  `${1}` is not tabstop syntax.
It is snippet mirror syntax.
