### ISSUE TITLE
Pressing <Space> while in a LaTeX \section{} adds '<`0:TARGET`>}' to the buffer

### ISSUE THREAD

**Issue by glacambre** [Shougo/neosnippet.vim#401]
How to reproduce:
Load neosnippet.vim and neosnippet-snippets. `:let g:tex_flavor = "latex"`, `:enew`, `:set ft=tex`. Then `isection<TAB><TAB>`.
This happens with NVIM v0.2.1-893-g126b2ca07 and Neosnippet 5.0.

**Comment by glacambre** [comment]
Sorry, forgot to mention that <TAB> is nnoremaped to this:
```vim
imap <expr> <Tab> exists('*neosnippet#expandable_or_jumpable()') && neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<Tab>"```

**Comment by Shougo** [comment]
It is the feature.
neosnippet is the marker snippet plugin.

**Comment by glacambre** [comment]
I'm sorry, I probably didn't state my problem clearly. I recorded a [video](https://my.mixtape.moe/dshmej.webm) of the bug, could you tell me if this is really supposed to happen?
Each `<``0:TARGET``>}` is added after I press `<TAB>`.

**Comment by Shougo** [comment]
I cannot watch the webm video.
Please use asciinema instead.
https://asciinema.org/

**Comment by Shougo** [comment]
It seems the feature.
Because,

```
snippet \section
alias   section \section{
    \section{${1}}
    ${0:TARGET}
```

section snippet is defined in neosnippet-snippets.

**Comment by glacambre** [comment]
Here's the [asciinema](https://asciinema.org/a/bMBwgrzd5fhB4be2B0agbKSK1). Sorry about the video not working (it works on my end).

**Comment by Shougo** [comment]
It is the feature.
Because `\section{` snippet is defined.

**Comment by Shougo** [comment]
You have executed `<Plug>(neosnippet_expand_or_jump)` by `<Space>`.
So `\section{` is expanded.

**Comment by glacambre** [comment]
Oh, I think I understand now. Thank you for your help and I apologize for bothering you with this.

**Comment by Shougo** [comment]
You can use `<Plug>(neosnippet_jump_or_expand)` or `<Plug>(neosnippet_jump)` instead.
