### ISSUE TITLE
Functions not recognized by #enable_completed_snippet

### ISSUE THREAD

**Issue by TxHawks** [Shougo/neosnippet.vim#402]
I have the following javascript code:
```js
function test(a, b) { return a* b; }
```

With the following neosnippet configuration:
```vim
  let g:neosnippet#enable_completed_snippet = 1

  imap <C-e>     <Plug>(neosnippet_expand_or_jump)
  smap <C-e>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-e>     <Plug>(neosnippet_expand_target)

  " Marker concealment
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
```

When I type `function` in the following line and then `<c-e>`, the `function` snippet is expanded as expected. However, nothing happens when I type `test` and then `<c-e>`

A minimal rc file reproducing this behavior can be found [here](http://dev.txh.io/minimal.vim)

`nvim --version`:
```sh
NVIM v0.2.1-dev
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170821-82934-fnjf1/build/config -I/tmp/neovim-20170821-82934-fnjf1/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170821-82934-fnjf1/build/src/nvim/auto -I/tmp/neovim-20170821-82934-fnjf1/build/include
Compiled by txh@frontier

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-8d1ccb6_1/share/nvim"
```

**Comment by Shougo** [comment]
It is the feature.

The `completed_snippet` feature is worked after completion only.
Not expanded snippet.

**Comment by TxHawks** [comment]
Thanks for getting back to me/
Thing is, it also doesn't show up in the suggestion list from deoplete

**Comment by Shougo** [comment]
> Thing is, it also doesn't show up in the suggestion list from deoplete

Java script completion plugin is needed.

**Comment by TxHawks** [comment]
suggestions from tern and the language-client do show up. Anything special I need to do for adding neosnippet as a js source?

**Comment by Shougo** [comment]
Ah, `test(` and `<C-e>` is needed.

**Comment by TxHawks** [comment]
Sorry, I'm not really clear on what that means... Can you post an example?

Thank you so much for being so responsive. It is really appreciated.

**Comment by Shougo** [comment]
* You must select `test` candidate from the completion popup
* The candidate must be contains the function prototype
* If you have completed the candidate, you can expand it by `<C-e>`

**Comment by TxHawks** [comment]
Not sure why, but it doesn't seen to work
![test](https://user-images.githubusercontent.com/5658514/31055428-6346b608-a6cb-11e7-8939-120cf4e043bb.gif)

**Comment by TxHawks** [comment]
One thing I noticed is that when I select the candidate from the completion list, it completes `test` not `test(`. Is that the issue?

**Comment by Shougo** [comment]
> Not sure why, but it doesn't seen to work

You have selected test candidate, but it does not contains the function prototype.

Please see:

> The candidate must be contains the function prototype

> One thing I noticed is that when I select the candidate from the completion list, it completes test not test(. Is that the issue?

It is not the problem.

**Comment by TxHawks** [comment]
Behavior is the same when I pick a candidate that does include the function
prototype (from tern or the language server). I'll upload a gif later when
I'm in front of a computer

**Comment by Shougo** [comment]
Really?  I have seen that you have selected the `[A]`(around source) candidate.

**Comment by Shougo** [comment]
http://dev.txh.io/minimal.vim

It does not include tern or language server.

**Comment by TxHawks** [comment]
`miniml.vim` doesn't have them, but my regular config does:

```vim
Plug 'autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'ternjs/tern_for_vim', { 'do': 'yarn', 'for': ['javascript'] }
Plug 'carlitux/deoplete-ternjs', {'do': 'yarn global add tern', 'for': ['javascript']}
Plug 'Shougo/echodoc.vim'
Plug 'Shougo/neosnippet'
Plug 'Shougo/neosnippet-snippets'
```
Do I need to explicitly set `g:deoplete#sources`?

Here is a gif of try to expand after selecting a language server source:

![vim](https://user-images.githubusercontent.com/5658514/31068466-c75eef44-a760-11e7-9632-670989a5349b.gif)

**Comment by Shougo** [comment]
Please upload autozimu/LanguageClient-neovim configuration and the sample JavaScript file.
I will try it later.

**Comment by TxHawks** [comment]
Updated [minimal.vim](http://dev.txh.io/minimal.vim) and uploaded the [sample `js`](http://dev.txh.io/getunit.js) from the gif above

**Comment by Shougo** [comment]
The sample js is 404 not found.
Please reupload it.

**Comment by TxHawks** [comment]
Sorry for that. 

I created a repository with all the required files (including what you need to get completion candidates from the language server):
[txhawks/neosnippet-repro](https://github.com/txhawks/neosnippet-repro)

Thank you again

**Comment by Shougo** [comment]
OK.  It worked.
Please rename the function name like this.

```vim
 /* @flow */
function test_foobar(a: number, b: number): number  {
  return a + b;
} 
```

**Comment by Shougo** [comment]
My minimal init.vim

```
set rtp+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim/
set rtp+=~/.cache/dein/repos/github.com/Shougo/neosnippet.vim/
set rtp+=~/src/LanguageClient-neovim/

let g:deoplete#enable_at_startup = 1

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ 'javascript': ['node', '/home/shougo/src/javascript-typescript-langserver/lib/language-server-stdio.js'],
    \ }

" Automatically start language servers.
let g:LanguageClient_autoStart = 1

let g:neosnippet#enable_completed_snippet = 1

imap <C-e>     <Plug>(neosnippet_expand_or_jump)
smap <C-e>     <Plug>(neosnippet_expand_or_jump)
xmap <C-e>     <Plug>(neosnippet_expand_target)

" Marker concealment
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
```

**Comment by TxHawks** [comment]
Why is the underscore required? It's not common practice to name things like that in JavaScript, where camelCase is the norm

**Comment by Shougo** [comment]
> Why is the underscore required? It's not common practice to name things like that in JavaScript, where camelCase is the norm

The underscore is not needed.
But `test` should not be used.
It is the same name with the other module function.

**Comment by TxHawks** [comment]
Okay, strangely enough, his works with the typescript-javascript language server, but not with the flow one.

I'll open an issue there. Any ideas for specifics I should be asking for in order for this to work?

**Comment by Shougo** [comment]
Sorry, I don't know ...
