### ISSUE TITLE
Is it possible to run expression evaluation on synchronized placeholder?

### ISSUE THREAD

**Issue by rawaludin** [Shougo/neosnippet.vim#404]
I want to create snippet that will change use my placeholder text in two place, one with its current  form and another one with MixedCase form. Vim abolish already have this function to change text form to camelCase eg. `my_field` to `myField` (using `g:Abolish.camelcase(...)`) or `MyField` (using `g:Abolish.mixedcase(...)`).

https://github.com/tpope/vim-abolish/issues/29

Eg my resulting text would be this, by only inserting `my_field`:

```
    /**
     * Set my_field attribute.
     */
    public function setMyField($value);

    /**
     * Get my_field attribute.
     */
    public function getMyField();
```

Is it possible? Thanks

**Comment by Shougo** [comment]
Unfortunately, it cannot.
In deoppet.nvim, it can be implemented.
