### ISSUE TITLE
Markers not concealed after an extended NeoVim session

### ISSUE THREAD

**Issue by jeromedalbert** [Shougo/neosnippet.vim#406]
I have `set conceallevel=2 concealcursor=niv` in my vimrc, and it works well most of the time. For example when I expand one of my snippets it becomes:

```
    describe 'description' do
      
    end
```

After a certain amount of time though, when I expand snippets, it shows the conceal marker like this:

```
    describe 'description' do
      <`0`>
    end
```

But when I check `echo &conceal`, it is still `2`, and `echo &concealcursor` is still `niv`. So theoretically it should be hidden, but in practice it shows. I have to restart NeoVim for it to work again.

What is hard here is that I can't find a way to reproduce the problem consistently. All I can say is that it happens after a while when working in NeoVim. I also use tmux. Any idea on how to figure this problem out?

**Comment by Shougo** [comment]
Please check `verbose setlocal conceallevel?` and `verbose setlocal concealcursor?`.
I think other plugins overwrite them.
