### ISSUE TITLE
Support extends

### ISSUE THREAD

**Issue by archSeer** [Shougo/neosnippet.vim#407]
Some `.snippets` files have an `extends` declaration. For example, [vue extends html, js, css](https://github.com/honza/vim-snippets/blob/master/snippets/vue.snippets#L5) to enable those snippets under the vue filetype.

**Comment by archSeer** [comment]
Maybe the snipmate implementation can help: https://github.com/garbas/vim-snipmate/commit/db6836968bd698da67117c105e690288a1e6850f

**Comment by Shougo** [comment]
Ah, OK.
neosnippet has the same feature "include".

**Comment by archSeer** [comment]
Ah sorry, forgot to mention: I'm using `honza/vim-snippets`, so it's the snipmate syntax, not neosnippet :/ Would it be possible to add that to the snipmate compatibility mode?

**Comment by Shougo** [comment]
neosnippet should support the feature.

**Comment by Shougo** [comment]
I have implemented it.

**Comment by archSeer** [comment]
Thank you for your continual work on neosnippet & deloplete! 🍻
