### ISSUE TITLE
<tab> to expand/jump after remapping <c-k> and <c-n>

### ISSUE THREAD

**Issue by boojum** [Shougo/neosnippet.vim#408]
minimal [init.vim](http://vpaste.net/55dFA)

After remapping `<c-n>`/`<c-p>` to `<c-j>`/`<c-k>` I can not get `<tab>` to work with `neosnippet_expand_or_jump` correctly.

Desired behaviour is for `<tab>` to expand or jump to placeholder. Only expanding is working, and not exactly as expected - after expanding there is `<`0`>` inserted at the end of the expanded line. Jumping to another placeholder is not working at all.

Are my keybindings wrong or is it an issue with `neosnippet`?

**Comment by Shougo** [comment]
>  after expanding there is `<0>` inserted at the end of the expanded line.

It is the feature of neosnippet.

Please read the documentation example.

```vim
imap <expr><tab> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : pumvisible() ? "\<c-j>" : "\<tab>"
smap <expr><tab> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
```
