### ISSUE TITLE
Support LSP style snippet

### ISSUE THREAD

**Issue by autozimu** [Shougo/neosnippet.vim#412]
Language server protocol defines a slightly different snippet syntax. Is it possible to support it within this plugin? Thanks.

LSP snippet syntax: https://github.com/Microsoft/language-server-protocol/blob/master/snippetSyntax.md

Relate issues
1. https://github.com/autozimu/LanguageClient-neovim/issues/294
2. https://github.com/autozimu/LanguageClient-neovim/issues/232
3. https://github.com/roxma/nvim-completion-manager/issues/172

**Comment by Shougo** [comment]
OK, but it should be implemented in deoppet.nvim.
neosnippet is hard to extend.
