### ISSUE TITLE
Support SnipMate description syntax

### ISSUE THREAD

**Issue by jsit** [Shougo/neosnippet.vim#416]
[SnipMate](https://github.com/garbas/vim-snipmate/blob/master/doc/SnipMate.txt) supports a description/abbreviation syntax like this:

`snippet trigger optional description`

The equivalent to neosnippet's:

```
snippet trigger
abbr optional description
```

It would be great if neosnippet would support the former syntax when `g:neosnippet#enable_snipmate_compatibility` is set to `1`.

**Comment by Shougo** [comment]
It is already supported.

**Comment by jsit** [comment]
But the trigger becomes the entire string with underscores where the spaces were, right?

**Comment by Shougo** [comment]
> But the trigger becomes the entire string with underscores where the spaces were, right?

Yes.  It is the feature.
Because, neosnippet snippet triggers must be unique name.
snipMate allows duplicate snippet trigger.

**Comment by jsit** [comment]
Is it possible to make it so that the trigger isn't that huge string with underscores, and just the part before the second space? I guess this was my request.

**Comment by Shougo** [comment]
Hm...  OK.

**Comment by Shougo** [comment]
> For instance, maybe don't support duplicate triggers. Otherwise, how is one supposed to remember such long snippet triggers?

You should use auto completion plugin like deoplete.

**Comment by jsit** [comment]
In that case the pop up menu gets very, very wide, and becomes difficult to read.

**Comment by Shougo** [comment]
So, I will shortening the trigger.
