### ISSUE TITLE
Master breaks the `enable_completed_snippet` feature for auto generated snippets

### ISSUE THREAD

**Issue by svanharmelen** [Shougo/neosnippet.vim#417]
With this is my `init.vim` file:

```
call plug#begin('~/.config/nvim/plugged')
Plug 'shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-go', { 'do': 'make' }
Plug 'shougo/neosnippet'
Plug 'fatih/vim-go'
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:neosnippet#enable_completed_snippet = 1
```

Expansion of auto generated snippets don't work anymore since commit b500600c56c42a190bff12b9560c9f46a81a45b9
  
To reproduce add `imap <expr><CR> neosnippet#expandable() ? "\<Plug>(neosnippet_expand)" : "\<CR>"` to the `init.vim` example and do:
1. Open a Go source file
2. Type `fmt.`
3. From the completions select `fmt.Errorf` and press `<CR>`

Before commit b500600c56c42a190bff12b9560c9f46a81a45b9:
![before](https://user-images.githubusercontent.com/4171547/36204563-0314c6ae-118c-11e8-93f2-b744b630459d.gif)

After commit b500600c56c42a190bff12b9560c9f46a81a45b9:
![after](https://user-images.githubusercontent.com/4171547/36204568-0818116a-118c-11e8-823a-03effc6e2f4f.gif)

As you can see, nothing happens now after pressing `<CR>`

**Comment by joshuarubin** [comment]
I've found that swapping the first two cases (`abbr` and `info`) in the `# Set abbr` section fixes the issue for me, though I don't know if the ordering was significant for other reasons.

```vim
  " Set abbr
  let abbr = ''
  if get(item, 'abbr', '') =~# '^.\+('
    let abbr = item.abbr
  elseif get(item, 'info', '') =~# '^.\+('
    let abbr = matchstr(item.info, '^\_s*\zs.*')
  elseif get(item, 'menu', '') =~# '^.\+('
    let abbr = item.menu
  elseif item.word =~# '^.\+(' || get(item, 'kind', '') == 'f'
    let abbr = item.word
  endif
  let abbr = escape(abbr, '\')
```

**Comment by Shougo** [comment]
Yes.  I know that.
But it is workaround.

**Comment by svanharmelen** [comment]
Works as expected again. Thanks!
