### ISSUE TITLE
overwriding error message

### ISSUE THREAD

**Issue by itchyny** [Shougo/neosnippet.vim#420]
Using neosnippet.vim plus neosnippet-snippets, setting filename to sql causes the following error.
```
[neosnippet] /path/to/neosnippet-snippets/neosnippets/sql.snip:8 is overriding `CREATE` from /path/to/neosnippet-snippets/neosnippets/sql.snip:1
[neosnippet] Please rename the snippet name or use `delete CREATE`.
[neosnippet] /path/to/neosnippet-snippets/neosnippets/sql.snip:46 is overriding `SELECT` from /path/to/neosnippet-snippets/neosnippets/sql.snip:38
[neosnippet] Please rename the snippet name or use `delete SELECT`.
```
From https://github.com/Shougo/neosnippet-snippets/blob/5902053e0202248f0855d7a2b4f562425447493e/neosnippets/sql.snip#L8, it is surely duplicated snippet but the code is not updated for long time.
```sql
snippet     CREATE TABLE
abbr        CREATE TABLE { ... }
options     head
  CREATE TABLE ${1:cities} (
    ${0:name varchar(80), country_name text}
  );

snippet     CREATE INDEX
abbr        CREATE INDEX ... ON ... ( ... )
options     head
  CREATE INDEX ${1:_name} ON ${2:cities} (${3:name});
```
I git-blamed the code and found 3071a45a4cc9e9702a05c4c61c363ce8d6173fe2 was the first bad commit. And I also noticed that `let g:neosnippet#enable_snipmate_compatibility = 1`  causes no error.

So the question is

- Shoud we set enable_snipmate_compatibility on when using neosnippet-snippets? If yes, that should be noted in README.md.
- Or the commit 3071a45a4cc9e9702a05c4c61c363ce8d6173fe2 introduced some unexpected behaviour? Then it should be reverted or fixed for neosnippet-snippets users.
- Or the snippet for sql in neosnippet-snippets is incorrect?

**Comment by Shougo** [comment]
It is neosnippet-snippets error.
neosnippet is right.
