### ISSUE TITLE
Argument of extend() must be a List or Dictionary

### ISSUE THREAD

**Issue by mmrath** [Shougo/neosnippet.vim#422]
Error detected while processing function neosnippet#init#_initialize[4]..<SNR>221_initialize_cache[2]..neosnippet#comman
ds#_make_cache[22]..neosnippet#parser#_parse_snippets[19]..neosnippet#helpers#vim2json:
line    1:
E117: Unknown function: js_encode
Press ENTER or type command to continue
Error detected while processing function neosnippet#init#_initialize[4]..<SNR>221_initialize_cache[2]..neosnippet#comman
ds#_make_cache[22]..neosnippet#parser#_parse_snippets[19]..neosnippet#helpers#vim2json:
line    1:
E15: Invalid expression: has('patch-7.4.1498') ? js_encode(a:expr) : string(a:expr)
Press ENTER or type command to continue
Error detected while processing function neosnippet#init#_initialize[4]..<SNR>221_initialize_cache[2]..neosnippet#comman
ds#_make_cache:
line   22:
E712: Argument of extend() must be a List or Dictionary

**Comment by Shougo** [comment]
Your neosnippet version is too old.
Please update it to the latest version.
