### ISSUE TITLE
Unexpected behavior: jumping between markers

### ISSUE THREAD

**Issue by fastbodin** [Shougo/neosnippet.vim#423]
**Problem Summary**
When dealing with multiple nested snippets, the order of the markers seems to get indexed wrong.
 
**Steps to reproduce**
1. Use the following minimal vimrc
```
set nocompatible
set runtimepath+=~/path/to/neosnippet.vim/
filetype plugin indent on
let g:neocomplete#enable_at_startup = 1
let g:neosnippet#snippets_directory = '~/snippets'

imap <expr><TAB> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : (pumvisible() ? "\<C-n>" : "\<TAB>")
smap <expr><TAB> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
```
2. Input the following snippets into a plaintex.snippets file in ~/snippets
```
snippet equn
abbr "Equation"
    \begin{equation${1}}
            ${2} &= ${3} \\\\ ${4}
    \end{equation$1}
    ${5}

snippet br
abbr   "( ) - bracket"
    \left( ${1} \right) ${2}

snippet frac
abbr "Fraction"
    \frac{${1}}{${2}} ${3}
```
3. Run nvim test.tex
4. Type the following keystrokes
```
equn <TAB> <TAB> br <TAB> frac <TAB> <TAB> <TAB> <TAB> <TAB> <TAB> <TAB>
``` 

**Expected behavior**
Everything is fine up to
```
equn <TAB> <TAB> br <TAB> frac <TAB> <TAB> <TAB>
``` 
I would expect the following key strokes would take the cursor to the following markers
* TAB -> '<2>'
* TAB -> '<3>'
* TAB -> '<4>'
* TAB -> '<5>'

**Actual behavior**
The fourth TAB after 'frac' should have gone to marker '<2>' but instead when to marker '<4>'.  The following four keystrokes take the cursor to the following markers out of the expected order
* TAB -> '<4>'
* TAB -> '<2>'
* TAB -> '<3>'
* TAB -> '<5>'

There seems to be a problem with nesting snippets. It may be how I have defined them?

**Environment Information**
* OS: macOS High Sierra version 10.13.3
* neovim/Vim version: NVIM v0.2.2
* Neosnippet version: Version: 5.0

**:CheckHealth Output**
```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/opt/python@2/bin/python2
  - INFO: Python2 version: 2.7.14
  - INFO: python2-neovim version: 0.2.4
  - OK: Latest python2-neovim is installed: 0.2.4

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.4
  - INFO: python3-neovim version: 0.2.4
  - OK: Latest python3-neovim is installed: 0.2.4

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
  - WARNING: Missing "neovim" gem.
    - ADVICE:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

## Node provider (optional)
  - WARNING: `node` and `npm` must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` commands work.
```

**Screen shots**

![screen shot 2018-03-07 at 5 04 08 pm](https://user-images.githubusercontent.com/35845723/37127307-0a80db40-222a-11e8-898e-fcb9e87f9ebe.png)

![screen shot 2018-03-07 at 5 04 34 pm](https://user-images.githubusercontent.com/35845723/37127318-1621ba82-222a-11e8-8f37-af46bedf095c.png)

![screen shot 2018-03-07 at 5 09 24 pm](https://user-images.githubusercontent.com/35845723/37127382-53fcb3b6-222a-11e8-958e-54b758895491.png)

![screen shot 2018-03-07 at 5 05 45 pm](https://user-images.githubusercontent.com/35845723/37127329-202218b0-222a-11e8-8e32-c93bea6af305.png)

![screen shot 2018-03-07 at 5 05 57 pm](https://user-images.githubusercontent.com/35845723/37127333-220b2400-222a-11e8-8e70-8c9d233dffe6.png)

![screen shot 2018-03-07 at 5 06 08 pm](https://user-images.githubusercontent.com/35845723/37127334-23b02620-222a-11e8-8c1d-7b858ca912e2.png)

![screen shot 2018-03-07 at 5 06 18 pm](https://user-images.githubusercontent.com/35845723/37127336-255204f8-222a-11e8-90ca-f8e5b81c0056.png)

![screen shot 2018-03-07 at 5 06 51 pm](https://user-images.githubusercontent.com/35845723/37127339-26d10bc6-222a-11e8-81bd-64c3f5fa9b76.png)

![screen shot 2018-03-07 at 5 11 20 pm](https://user-images.githubusercontent.com/35845723/37127437-96772c3a-222a-11e8-9791-9765ffc4f0d8.png)

**Comment by fastbodin** [comment]
Understood. Thanks for the quick response.

**Comment by Shougo** [comment]
I should implement deoppet.nvim(the next snippet plugin) instead.
I have not much time now though.

**Comment by fastbodin** [comment]
I was going to ask whether this sort of functionality would likely be implemented in deoppet.nvim. I appreciate your work. I have been looking forward to eventually using deoppet.nvim. Just have been unsure when would be best to make the conversion over.

**Comment by Shougo** [comment]
Of course, deoppet.nvim should support nested snippet expansion without markers.
I think it is possible.

Current neosnippet has very many features.  It takes more time.
And I have other plugins development.
Especially, deoplete.

**Comment by fastbodin** [comment]
I understand. Il also use deoplete so I appreciate your work there! 

Il keep my eye on deoppet.nvim
