### ISSUE TITLE
How to skip some syntax elements?

### ISSUE THREAD

**Issue by lex-ushakov** [Shougo/neosnippet.vim#424]
Hello,

let's get, for example, `java` `class` snippet.
```
class  extends Parent implements Interface {
  TARGET
}
```
and use [default](https://github.com/Shougo/neosnippet.vim#configuration) config.

How to create class that not extends other classes and not implements interfaces?
(removes `extends Parent implements Interface`)

**Comment by Shougo** [comment]
Please update neosnippet-snippets.
