### ISSUE TITLE
The snippet unfolds in quotes ( " , ' )

### ISSUE THREAD

**Issue by D1mon** [Shougo/neosnippet.vim#425]
Snippet name: static

Not working:
`<link rel="stylesheet" href="static" />`

If you put a space in the beginning, then it does not show that we have a snippet, but the snippet unfolds. If you put spaces around the word, then everything works as it should.
`<link rel="stylesheet" href=" static " />`

**Comment by Shougo** [comment]
```
Q: What if I want to expand a snippet trigger after (, [, " etc...:

A: You should use "options word" in the snippet definition. This changes the
expansion behavior to a word boundary or set
|g:neosnippet#expand_word_boundary|.
>
	snippet     date
	options     word
	    `strftime("%d %b %Y")`
<
```

Please read the documentation.
