### ISSUE TITLE
Should deoplete be added to installation instructions?

### ISSUE THREAD

**Issue by zubin** [Shougo/neosnippet.vim#428]
The README currently says:

> neocomplcache/neocomplete is not required to use neosnippet, but it's highly recommended.

But both of these are inactive, and one recommends using deocomplete:

> Note: If you use neovim or Vim8+, you should use deoplete instead. https://github.com/Shougo/deoplete.nvim

However the installation instructions here make no mention of deoplete.

What is the recommended installation with latest version of neovim? (or vim 8+)

**Comment by Shougo** [comment]
Oh, I should fix the documentation.
