### ISSUE TITLE
Ignoring/overriding specified snippets

### ISSUE THREAD

**Issue by naquad** [Shougo/neosnippet.vim#429]
It would be nice to have an option to don't load default snippets of given filetype, but still load user ones.

A particular use case I've got is PHP language completions: I'm working with framework and lots of default snippets are not relevant or even make it harder to work with it. I wrote my own snippets, but default ones still adding triggers I'm using often so editing can become a struggle.

**Comment by Shougo** [comment]
I think improving neosnippet-snippets is better.

But you can use `g:neosnippet#disable_runtime_snippets` for it.

**Comment by naquad** [comment]
It will disable *all* snippets while I need to override only 1 file type.

**Comment by Shougo** [comment]
@naquad Please read the documentation.
It is not only for one filetype.

```
				*g:neosnippet#disable_runtime_snippets*
g:neosnippet#disable_runtime_snippets
		This is a dictionary variable which uses file types as key.
		If you set the value of a file type entry to 1, this prevents
		loading "neosnippets" directories from 'runtimepath'. This is
		very useful to prevent snippet conflicts between self defined
		snippet files and the built-in snippet files of neosnippet. If
		you use an "_" as key for an entry this will treat the value of
		the entry as default value for all file types.
```
