### ISSUE TITLE
Simple snippet does unexpected behaviour

### ISSUE THREAD

**Issue by pavilion** [Shougo/neosnippet.vim#431]
So I have this snippet, a simple function-body expression for js
`snippet    fb
    (${1}) = > {
        ${2}
}
`
When I use it I somehow get 3 placeholders (instead of 2), the third one places at the end, like this:
`snippet    fb
    (${1}) = > {
        ${2}
} {here}
`
Here is my [.vimrc](https://github.com/pavilion/vimrc/blob/master/.vimrc) files 
I only have that problem with that snippet, other snippets work flawlessly. Thanks for your amazing work in every of your repos! I use them all!

**Comment by Shougo** [comment]
It is feature.

One line snippet will be converted like this.

`snippet fb (${1}) = > { ${2} }` to `snippet fb (${1}) = > { ${2} }${0}`

**Comment by pavilion** [comment]
Hi, it's actually not one line, but GitHub formatted it like that. This is how it looks in the snippets file:
![image](https://user-images.githubusercontent.com/3165436/41037909-978b1cf4-698c-11e8-8861-ccee1c870250.png)
![image](https://user-images.githubusercontent.com/3165436/41037823-4fe1b41c-698c-11e8-9cc5-ea04799007ef.png)
If that is actually a feature... May I ask how should I write my snippet? Thanks

**Comment by Shougo** [comment]
If you want to disable the feature, you must use `${0}` like this.

```
snippet fb
    (${1}) = > {
        ${0}
     }
```
