### ISSUE TITLE
Wrong "You must install neosnippet-snippets or disable runtime snippets" warning

### ISSUE THREAD

**Issue by hasufell** [Shougo/neosnippet.vim#432]
vim config with vim-plug:

```vim
call plug#begin('~/.vim/plugged')

if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif

Plug 'Shougo/neosnippet.vim'
Plug 'honza/vim-snippets'

call plug#end()


" Enable snipMate compatibility feature.
let g:neosnippet#enable_snipmate_compatibility = 1

" deoplete
let g:deoplete#enable_at_startup = 1
```

On start, it shows `You must install neosnippet-snippets or disable runtime snippets`, which is wrong. Because I do have snippet via `honza/vim-snippets`. Disabling runtime snippets disables those too, so that is definitely not what I want. The warning is simply wrong.

**Comment by hasufell** [comment]
I wrote a patch [here](https://gogs.hasufell.de/hasufell/neosnippet.vim/commit/6384ba8e367a4ccc7fbcc947c4de8d5b53c0211e)

You can fetch the branch (sorry, I don't like github):

```sh
git fetch https://gogs.hasufell.de/hasufell/neosnippet.vim.git PR/fix-warning
```

**Comment by Shougo** [comment]
OK.  I get the problem.
I have fixed.

**Comment by Shougo** [comment]
Because I have got the reason and easy to fix.

**Comment by hasufell** [comment]
> Because I have got the reason and easy to fix.

Yes, that was exactly [my patch](https://gogs.hasufell.de/hasufell/neosnippet.vim/commit/6384ba8e367a4ccc7fbcc947c4de8d5b53c0211e). But you recreated the patch without giving any attribution, which I find quite rude.

**Comment by Shougo** [comment]
Sorry.  I should add the comment for it.

I just want to fix it easily.

**Comment by Shougo** [comment]
> Was there a problem with fetching from my repository?

I know you don't like github.
But please send for me to PR.  I have seen that you have sent the PRs to other open source projects.
PR is easy to review and include.

This is my thought when https://github.com/Shougo/neosnippet.vim/issues/432#issuecomment-397861449.

* I need to execute the command to include the patch.
* But the reason is very simple.
* Hm...  It is easy fix for me.

It is my mistake though.

**Comment by Shougo** [comment]
The command is just one.
But it needs `one` command.

**Comment by Shougo** [comment]
> Yes, that was exactly my patch. But you recreated the patch without giving any attribution, which I find quite rude.

I can add the attribution, but the commit is already committed.
I cannot fix/add the message..

**Comment by hasufell** [comment]
> It is risk vs convenience.

That is true. But we as users also have some kind of power to say what we like and what we don't. Sourceforge also died a very quick death after they betrayed their users.

I think it's fair to use a free git service like github and I don't tell people how to run their projects. But I think it's also good to accept patches via alternative channels. Git makes this relatively easy. Imagine we would still have to send patches in `.tar.gz` format :)

Thanks for fixing this issue, btw!

**Comment by Shougo** [comment]
> That is true. But we as users also have some kind of power to say what we like and what we don't. Sourceforge also died a very quick death after they betrayed their users.

Yes.  github may be died if microsoft is evil.
I like github though...  (I use github from long years ago in 2008)

> I think it's fair to use a free git service like github and I don't tell people how to run their projects. But I think it's also good to accept patches via alternative channels. Git makes this relatively easy. Imagine we would still have to send patches in .tar.gz format :)

github is easy.  But I may accept alternative way.  OK.

**Comment by Shougo** [comment]
Note:  Thank you for reporting the problem.
I cannot find the problem until you have reported.
