### ISSUE TITLE
Easiest way to disable global snippets?

### ISSUE THREAD

**Issue by uinput** [Shougo/neosnippet.vim#440]
Hi,

I know this has been asked in some issues already, but I still could not figure out what the recommended way of disabling the global snippets is.

I'm using Shougo's `neosnippet-snippets` and I'm pretty comfortable with most of the snippets, except the global ones defined in `_.snip`. We cannot disable them using `g:neosnippet#disable_runtime_snippets` because the `_` key matches all filetypes. Also, we cannot use the `delete` keyword, because this keyword only deletes snippets defined in the same file (or sourced from the file) previously.

Now, what is the recommended way of disabling the predefined global snippets? Do I have to clone the whole `neosnippet-snippets` repository just to have them excluded?

Thanks!

**Comment by Shougo** [comment]
Nothing unfortunately.
>  Do I have to clone the whole neosnippet-snippets repository just to have them excluded?

Yes.

**Comment by uinput** [comment]
Couldn't we make it so `*` excludes _all_ patterns, while the `_` key is reserved to exclude _global_ patterns?

For now, I overwrote the snippets like so:
```snip
snippet     date_english
    

snippet     datetime_iso8601
    

snippet     date_iso8601
    

snippet     time_colon
    

snippet     lastmod
    

snippet     filename
    

snippet     path
    

snippet     rpath
    

snippet     basename
    

snippet     filename_upper_camel
    

snippet     filename_lower_camel
    
```

**Comment by Shougo** [comment]
> Couldn't we make it so * excludes all patterns, while the _ key is reserved to exclude global patterns?

Yes.

I should fix the problem in deoppet.nvim.
But I cannot fix it in neosnippet.vim.
