### ISSUE TITLE
I get some weird marker on snippet expansion

### ISSUE THREAD

**Issue by dareenzo** [Shougo/neosnippet.vim#441]
Hi,

I think the attached gif illustrates it better, but I have this issue where
I'm able to expand snippets and also navigate through placeholders, but additionally get some weird markers (```<`01`>```) which confuse me. 
Whenever I see those markers, I get the impression that something is off and don't if its me or something else.

![converted](https://user-images.githubusercontent.com/6130991/44268019-95ca6780-a230-11e8-9a03-573d2b9d0b24.gif)

I wonder if this is a know issue? Am I missing something on the configuration? Or if you have hint on how I can fix it?

Thanks

**Comment by Shougo** [comment]
> I wonder if this is a know issue? Am I missing something on the configuration? Or if you have hint on how I can fix it?

It is feature.  But you can hide it.

```vim
	if has('conceal')
	  set conceallevel=2 concealcursor=niv
	endif
```
