### ISSUE TITLE
HTMLファイルの編集中にCSSも補完候補になってしまう

### ISSUE THREAD

**Issue by yoshinaga-hiroyuki** [Shougo/neosnippet.vim#442]
こちらは初めてになります
色々なプラグインでお世話になっていますが、吉永と申します

neosnippetとneosnippet-snippetsの組み合わせについての質問なのですが、こちらでよかったでしょうか
もしより適切な場が有れば、ご指摘頂ければ幸いです
### 質問内容
さて本題なのですが、表題通りHTMLの編集中にCSS、より具体的には
〜/github.com/Shougo/neosnippet-snippets/neosnippets/html.snip
だけでなく
〜/github.com/Shougo/neosnippet-snippets/neosnippets/css.snip
の分も補完候補になってしまいます
次の動画が動作例です
![neosnippet_html-css](https://user-images.githubusercontent.com/24851657/44625550-2e569b00-a947-11e8-95f9-c909167218c1.gif)
outlen以下の部分は、css.snipに記述分のなので、出てほしくないのです

元々は個人用のファイル
~/.vim/snippet/html.snip
にolタグの補完を追加しようとして気が付きました

普段は [osyo-manga/vim-precious](https://github.com/osyo-manga/vim-precious)を使っているので、CSSはstayleタグ/属性内で出てくれれば十分なので、タグ入力で出てくると邪魔にもなってしまいます
### 動作環境
> $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
$ uname -a
Linux naonari 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
適用済パッチ: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

下記の設定ファイルは、状況確認、動画撮影の為にコマンドの通り、一時的にコメントした内容は省いてあります
#### vimrc
> $ grep -vh "^\"" ~/.vim/vimrc | sed -r -e 's/\s*".+//g' -e '/^$/d'
```
if has('vim_starting')
if &compatible
set nocompatible
endif
let s:cache_home = empty($XDG_CACHE_HOME) ? expand('~/.vim') : $XDG_CACHE_HOME
let s:dein_dir = s:cache_home . '/bundle'
  let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if !isdirectory(s:dein_repo_dir)
  call system('git clone https://github.com/Shougo/dein.vim ' . shellescape(s:dein_repo_dir))
  endif
  set runtimepath+=~/.vim/bundle/repos/github.com/Shougo/dein.vim
  if dein#load_state(s:dein_dir)
call dein#begin(s:dein_dir)
  let g:rc_dir = expand('~/.vim/rc')
  let s:toml = g:rc_dir . '/dein.toml'
  let s:lazy_toml = g:rc_dir . '/dein_lazy.toml'
  call dein#load_toml(s:toml, {'lazy': 0})
  call dein#load_toml(s:lazy_toml, {'lazy': 1})
  call dein#end()
  call dein#save_state()
  if dein#check_install()
call dein#install()
  endif
  endif
  endif
  filetype plugin indent on
```
### dein.vimで管理しているプラグイン
> $ grep -vh "^\#" ~/.vim/rc/dein* | sed -r -e 's/ \#.+//g'  -e ''s/\v^\s*".+\n//g'

下記のlet g:neosnippet#snippets_directory 履けしてもやはり変化はありませんでした
```
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'Shougo/neocomplete'
hook_add = '''
	let g:neocomplete#enable_at_startup = 1
	let g:neocomplete#enable_ignore_case = 1
	let g:neocomplete#enable_smart_case = 1
	if !exists('g:neocomplete#keyword_patterns')
		let g:neocomplete#keyword_patterns = {}
	endif
	let g:neocomplete#keyword_patterns._ = '\h\w*' "_(アンダーバー)区切りの補完を有効化
	if !exists('g:neocomplete#force_omni_input_patterns')
		let g:neocomplete#force_omni_input_patterns = {}
	endif
	let g:neocomplete#sources#dictionary#dictionaries = { 'default' : '',}
'''
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['context_filetype']
hook_add = '''
	imap <C-u> <Plug>(neosnippet_expand_or_jump)
	smap <C-u> <Plug>(neosnippet_expand_or_jump)
	xmap <C-u> <Plug>(neosnippet_expand_target)
	imap <C-b> <Plug>(neosnippet_expand_or_jump)
	smap <C-b> <Plug>(neosnippet_expand_or_jump)
	xmap <C-b> <Plug>(neosnippet_expand_target)
	inoremap <expr><BS> neocomplete#smart_close_popup()
	let g:neosnippet#snippets_directory = [ '~/.vim/snippet/', '~/.vim/bundle/repos/github.com/' ]
	if has('conceal')                              "補完で続けての入力を示すマーカーを入力中は非表示
		setlocal conceallevel=2 concealcursor=niv
	endif
'''
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
depends = ['neosnippet']
```

**Comment by Shougo** [comment]
I have reproduced it.
It is context_filetype.vim's bug.

I have fixed it.  Please upgrade.

**Comment by yoshinaga-hiroyuki** [comment]
修正ありがとうございます
アップデート後
``:call dein#recache_runtimepath()
したら出なくなりました

osyo-manga/vim-preciousを使っていても、CSSはstyleタグ/属性内でも出ませんが、これまでよりは格段に使いやすくなりました

**Comment by Shougo** [comment]
> osyo-manga/vim-preciousを使っていても、CSSはstyleタグ/属性内でも出ませんが、これまでよりは格段に使いやすくなりました

その状態なら出るはずです。手元では再現しません。
動かないなら context_filetype.vim 内に issue を立ててください。

**Comment by yoshinaga-hiroyuki** [comment]
解りました
再度確認して、再現したら改めてisuueを立てます
