### ISSUE TITLE
Writing snippet for puppet

### ISSUE THREAD

**Issue by jas01** [Shougo/neosnippet.vim#450]
Hi everyone.

I see puppet is not in the list of snippet inside neosnippet-snippets. 

It's ok I will do it. 

My question is : Before using neovim+neosnippet I'm using vim+vim-snippet (I know I can still use vim-snippet with neovim) and they got a very nice feature inside the snippet.

For puppet some class inside the file

`modules/my_module/manifests/init.pp`

going to be start with

`class my_module { }`

and some class inside the file

`module/my_module/manifests/thing.pp`

going to by name by

`class my_module::thing {}`

and ultimately a class inside the file

`module/my_module/manifests/subthing/thing.pp`

will have the name

`class my_module::subthing::thing {}`

so I need to have a snippet for let say class some method to convert the name of the file to the name of the class. 

Is this possible with neosnippet ? (Before I google everything to see how to do it..) Forget to say I'm very dummy with writing something for vim.

**Comment by Shougo** [comment]
I don't want to add it.  But you can implement it.

Please read the implementation.
https://github.com/Shougo/neosnippet-snippets/blob/master/neosnippets/go.snip#L81
