### ISSUE TITLE
How to replace placeholder after complete?

### ISSUE THREAD

**Issue by williamhuang03** [Shougo/neosnippet.vim#451]
Hi, sorry I'm very new to this and could not figure it out from the documentation.
I'm using deoplete + neosnippet + cquery in nvim.

After auto-completing, how do I replace the placeholders? Example:
![image](https://user-images.githubusercontent.com/11184811/50700038-88fbb400-1017-11e9-87f2-6bcf86db7b13.png)

How can I convert add_numbers(${1:int a}, ${2: int b})$0 to add_numbers(1,2); ?

Here is my init.vim:
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
if dein#load_state('~/.cache/dein')
    call dein#begin('~/.cache/dein')

    call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
    call dein#add('Shougo/deoplete.nvim')
    if !has('nvim')
        call dein#add('roxma/nvim-yarp')
        call dein#add('roxma/vim-hug-neovim-rpc')
    endif

    call dein#add('mhartington/oceanic-next')
"    call dein#add('vim-airline/vim-airline')
"    call dein#add('vim-airline/vim-airline-themes')
    call dein#add('wsdjeg/dein-ui.vim')
    call dein#add('scrooloose/nerdtree')
    call dein#add('Shougo/neosnippet.vim')
    call dein#add('Shougo/neosnippet-snippets')
    call dein#add('autozimu/LanguageClient-neovim', {
                \ 'branch': 'next',     
                \ 'do': 'bash install.sh',
                \ })

    call dein#end()
    call dein#save_state()
endif
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_start_length = 1
let g:deoplete#enable_smart_case = 1

filetype plugin indent on
syntax enable

" Neosnippets
let g:neosnippet#disable_runtime_snippets = {
    \ '_' : 1,
    \ }

" Language Client configuration
set hidden
let g:LanguageClient_serverCommands = {
            \ 'cpp': ['/opt/cquery/bin/cquery',
            \ '--log-file=/tmp/cq.log', 
            \ '--init={"cacheDirectory":"/tmp/cquery/"}'] 
            \ }

" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)

imap <expr><TAB>
    \ pumvisible() ? "\<C-n>" :
    \ neosnippet#expandable_or_jumpable() ?
	\    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
	\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

if has('conceal')
    set conceallevel=2 concealcursor=niv
endif

**Comment by Shougo** [comment]
```vim
autocmd CompleteDone * call neosnippet#complete_done()
```
