### ISSUE TITLE
How to escape $ character for default placeholder?

### ISSUE THREAD

**Issue by roxma** [Shougo/neosnippet.vim#452]
Here're two snippets:

```
snippet  test1
options  head
  ${1:escape ${2:foobar\} value}

snippet  test2
options  head
  ${1:escape \${2:foobar\} value}
```

The `test1` has a nested placeholder, as described from neosnippet's doc. 

But suppose that, for some reason, I want **leteral string** `${2:foobar}`  to be part of the snippet placeholder. Then I created the `test2` snippet. But it still behaves as a nested placeholder.

How do I properly escape `$` character in this case?

**Comment by Shougo** [comment]
Please use below pattern.

```vim
snippet  test2
options  head
  ${1:escape \${2:foobar\} value}
```

**Comment by roxma** [comment]
![neosnippet vim-452](https://user-images.githubusercontent.com/4538941/51152829-7f403f00-18a8-11e9-9cab-d636902fe019.gif)

Unfortunately the escape doesn't seem to work...

**Comment by Shougo** [comment]
I have mistaked.  Below code is right.

```
snippet  test2
options  head
  ${1:escape \\${2:foobar\} value}
```
