### ISSUE TITLE
Undo the whole completion snippet

### ISSUE THREAD

**Issue by reaysawa** [Shougo/neosnippet.vim#453]
After expanding a snippet and changing some words, I'd like to be able to undo the whole snippet expanded it with some command (not _uuuuu_). `deoplete#undo_completion()` does not work.

I think a good way to do this would be to save the position from `:changelist` in some variable and then go back in the undotree to that point. If it's a bit complicated to implement, I am happy to help!

**Comment by Shougo** [comment]
Sorry.  It is not possible and I don't want to add new feature in neosnippet.
It can be implemented in deoppet.nvim though.
