### ISSUE TITLE
 Placeholder display can cancel？

### ISSUE THREAD

**Issue by PendragonSaber** [Shougo/neosnippet.vim#454]
i got  these，I hope that I get a better look at the vertical line, the placeholders are a bit ugly.I don't know where I am setting the error.

![1](https://user-images.githubusercontent.com/41671631/51318085-3ea51900-1a94-11e9-992b-db1fb1ada469.jpg)
![22](https://user-images.githubusercontent.com/41671631/51322554-b5481380-1aa0-11e9-8abc-1fa8a14077ca.png)

**Comment by Shougo** [comment]
Hm... multipost with gitter.
Please enable conceal to hide the placeholders.

```vim
set conceallevel=2 concealcursor=niv
```

**Comment by PendragonSaber** [comment]
> Hm... multipost with gitter.
> Please enable conceal to hide the placeholders.
> 
> ```viml
> set conceallevel=2 concealcursor=niv
> ```

@Shougo  I have added it recently, but it didn't work.
