### ISSUE TITLE
LanguageClient-Neovim Python Auto-snippets not working

### ISSUE THREAD

**Issue by rraks** [Shougo/neosnippet.vim#461]
I updated to the latest commit and pyls based snippet completion stopped working. Snippets for Go/Rust work fine. 
I've tracked the issue to start showing up after commit 1b05a09 on wards.

**Comment by Shougo** [comment]
Please upload the reproduce-able instructions.

If not, I will close the issue.

For example, this is reproduce-able issue.
https://github.com/autozimu/LanguageClient-neovim/issues/396

Please read your report.  It is not reproduce-able.

**Comment by Shougo** [comment]
I have said same response in it.

https://github.com/autozimu/LanguageClient-neovim/issues/396#issuecomment-457016555

**Comment by Shougo** [comment]
Hm.  I have tested LanguageClient+pyls.
It does not support snippet.

**Comment by Shougo** [comment]
I get the reason.  It seems LanguageClient-neovim problem.

https://github.com/autozimu/LanguageClient-neovim/issues/727

**Comment by Shougo** [comment]
Please update both deoplete and LanguageClient-neovim.

**Comment by rraks** [comment]
Everything works well now! Thanks!
