### ISSUE TITLE
Error when trying to complete empty snippet from Language server

### ISSUE THREAD

**Issue by rraks** [Shougo/neosnippet.vim#462]
When i try to expand snippet for a deoplete suggestion which does not have a snippet, I get the following 
error message. It would be nice if neosnippet just ignored empty snippet.

> Error detected while processing function neosnippet#mappings#expand_or_jump_impl[1]..neosnippet#mappings#_trigger[8]..neosnippet#mappings#expandable_or_jumpable[1]..neosnippet#mappings#expandable[2]..neosnippet#mappings#completed_expandab
le[5]..<SNR>63_get_completed_snippets[13]..neosnippet#parser#_get_completed_snippet:
line   23:
E474: Attempt to decode a blank string

**Comment by Shougo** [comment]
Please use the latest version of neosnippet.
