### ISSUE TITLE
Neovim exits insert mode if a snippet has no placeholders

### ISSUE THREAD

**Issue by e-kwsm** [Shougo/neosnippet.vim#465]
# Problems summary
As of 4903cf61966f824b4e603780c9e3871b28f77ba9, nvim exits insert mode when calling `neosnippet_expand_or_jump` on a snippet without placeholders.
Is it possible to behave as beforehand if a snippet has no placeholders?

## Expected
When calling `neosnippet_expand_or_jump` on a snippet without placeholders, cursor jumps to the end of the expanded one and stay in insert mode.

## Environment Information

 * neosnippet.vim version (SHA1): 4903cf61966f824b4e603780c9e3871b28f77ba9
 * OS: Debian 9.5
 * neovim/Vim `:version` output: NVIM v0.4.0-342-g299f32dc0129

## minimal init.vim/vimrc

```vim
set runtimepath+=/tmp/neosnippet.vim
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
let g:neosnippet#snippets_directory='/tmp/snippets'
```

## How to reproduce the problem from neovim/Vim startup

```shellsession
$ cd /tmp
$ git clone --depth 1 https://github.com/Shougo/neosnippet.vim
$ mkdir snippets
$ cat << EOF > snippets/_.snip
snippet lorem
	Lorem ipsum dolor sit amet
EOF
```

Then `nvim -u vimrc` and `ilorem<C-k>`.

**Comment by e-kwsm** [comment]
Thanks.

**Comment by e-kwsm** [comment]
@Shougo Unfortunately that is insufficient: when expanding a snippet that is not located at the end (e.g. `lorem` in `lorem blah blah`), cursor jumps to the end of line.

The commits affected snippets that assumes implicit `${0}` at ends; I will create PR to fix some of them.

**Comment by Shougo** [comment]
I have fixed it.  Please update neosnippet.
