### ISSUE TITLE
Deopleteのポップアップメニューでの自動展開

### ISSUE THREAD

**Issue by gjjjpg** [Shougo/neosnippet.vim#466]
私はDeopleteの補完に‹TAB›,‹S-TAB›をつかっているのですが、Snippetを補完する際に、ポップアップメニューを閉じずに、自動でSnippetを展開(neosnippet_expand)をすることは可能でしょうか？

**Comment by Shougo** [comment]
snippet の自動展開は `g:neosnippet#enable_complete_done` のみサポートしています。
これは補完候補を確定すると expand されます。
他のタイミングでの展開は副作用が大きすぎるのでサポートしていません。

**Comment by gjjjpg** [comment]
技術的に厳しいことかもしれませんが、需要は少なくないと思いますので、deoppetでは様々なタイミングでの展開をサポートして頂きたいです。

**Comment by gjjjpg** [comment]
技術的に厳しいことかもしれませんが、需要は少なくないと思いますので、deoppetでは様々なタイミングでの展開をサポートして頂きたいです。

**Comment by Shougo** [comment]
すみませんが、補完の選択時の自動展開はたとえ Vim がサポートしたとしても不可能です。
なぜかというと、補完選択時に展開してしまうと他の候補を選択できなくなるからです。
よく考えてみてください。
