### ISSUE TITLE
Using the same variable in a single snippet stopped working

### ISSUE THREAD

**Issue by bugeats** [Shougo/neosnippet.vim#468]
At one point this was working as expected:

```
snippet console-log
alias cl
options head
  console.log('>> ${0}', $0);
```

When the first `$0` is tabbed to, you can fill in a value. Upon tabbing to the next position, that value would be populated with what you just typed.

At some point there was an update and the above example stopped working. Instead of populating the second `$0`, it's just blank.

**Comment by Shougo** [comment]
Unfortunately, it is invalid syntax.  So it does not work.

You cannot use `$0` as mirror placeholder.

```vim
snippet console-log
alias cl
options head
  console.log('>> ${1}', $1);
```

It should work.

**Comment by bugeats** [comment]
Thanks buddy. You do good work.
