### ISSUE TITLE
Snippet format documentation?

### ISSUE THREAD

**Issue by good-idea** [Shougo/neosnippet.vim#470]
I'm writing some of my own snippets. I'm using those in neosnippet-snippets as a guide, but I don't fully understand the format. Are there docs somewhere for the format of these `.snip` files?

**Comment by good-idea** [comment]
Oh, of course, they're in the vim docs 🙄
https://github.com/Shougo/neosnippet.vim/blob/master/doc/neosnippet.txt

**Comment by Shougo** [comment]
Yes.
