### ISSUE TITLE
Snippets and LanguageClient-neovim: no indent, undesired synchronized placeholder

### ISSUE THREAD

**Issue by pappasam** [Shougo/neosnippet.vim#475]
Thanks for this awesome plugin! These fixes may be out of scope because they're related to language-servers that focus more on vscode. That said, maybe you'll consider it in-scope, so I'll outline the problems in case it helps you and/or others who run into similar issues.

## Problems

I've run into two issues using the latest version of this plugin with the latest version of LanguageClient-neovim.

1. Snippets completed from a language server do not expand tabs
2. The placeholders in vscode use the same symtax as neosnippet's synchronized placeholder ($1, not ${1}), which means snippet completion does not work as intended by the language-server.

## Gif

![COMPLETION](https://user-images.githubusercontent.com/3723671/66603169-92531780-eb79-11e9-844c-ca94915711f9.gif)

## Value of v:completed_item

```
{'word': 'license:
        name: $1', 'menu': '[LC] ', 'user_data': '{"lspitem":{"label":"license","kind":10,"documentation":"","insertText":"license:\n\tname: $1","insertTextFormat":2,"textEdit":{"range":{"start":{"line
":10,"character":2},"end":{"line":10,"character":6}},"newText":"license:\n\tname: $1"}},"snippet":"license:\n\tname: $1"}', 'info': '', 'kind': 'Property', 'abbr': 'license'}
```

## Environment

* Terminal (Alacritty, zshell)
* neovim 0.5.0
* neosnippet: commit hash 3838f45930e8d6c05807c925350585c48bd21a4b
* LanguageClient-neovim: commit hash ee6cdb0940d9c2c95f31488f7d463b2d12abcbc4
* Server: yaml-language-server: 0.4.1 (https://github.com/redhat-developer/yaml-language-server/tree/0.4.1)

*vimrc:*

```vim
let g:neosnippet#enable_completed_snippet = 1
let g:neosnippet#enable_complete_done = 1
let g:LanguageClient_serverCommands = {
      \ 'yaml': ['yaml-language-server', '--stdio'],
      \ }
```

**Comment by pappasam** [comment]
A custom function I've written to work around the problem in this special case (disabling enable_completed_* neosnippet variables):

```vim
function! s:format_yaml_snippet()
  " Find and replace things with $0, $1, $2, etc
  s/$\([0-9]\+\)/<`\1`>/g
  " Expand custom yaml snippet
  execute 's/\%x00	/\r'
        \ . repeat(' ', indent('.'))
        \ . repeat(' ', &shiftwidth)
        \ . '/g'
endfunction
command! FormatYamlSnippet call s:format_yaml_snippet()
```

**Comment by Shougo** [comment]
Fixed.

**Comment by pappasam** [comment]
Unfortunately, while the latest fix gets us closer, it ignores shiftwidth and does not convert the tab character to spaces. See below for a gif:

![only-indent](https://user-images.githubusercontent.com/3723671/66718010-075a6300-edad-11e9-942d-cb4e0c155b1f.gif)

Thanks for addressing this so quickly btw, your plugins are the best!

**Comment by Shougo** [comment]
Sorry.  It is feature.

**Comment by pappasam** [comment]
Possibly, but the same thing now happens with my Python language snippets that come directly from the neosnippet-snippets plugin. I suspect this may be a bug, not a feature:

![broken_python](https://user-images.githubusercontent.com/3723671/66718210-4f7a8500-edaf-11e9-80c0-0cce1d9fb6aa.gif)

**Comment by Shougo** [comment]
Please test the latest version of neosnippet.

**Comment by pappasam** [comment]
Python: now cares about current level of indentation, but has two levels of indentation:

![double-indent-python](https://user-images.githubusercontent.com/3723671/66718379-396dc400-edb1-11e9-9442-e129bf49f7fa.gif)

**Comment by pappasam** [comment]
Snippets coming from the language server for YAML are doing the correct thing now, for the most part. Two minor issues that I will document soon.

**Comment by pappasam** [comment]
1. there's one extra space created for the first snippet location

![yaml-extra-space](https://user-images.githubusercontent.com/3723671/66718424-d29cda80-edb1-11e9-9e51-5f4745e2eb6c.gif)

**Comment by Shougo** [comment]
> there's one extra space created for the first snippet location

Please upload `v:completed_item` result.

**Comment by pappasam** [comment]
2. Spuriously (not every time), the first "jump to next symbol" inserts the snippet again when using this key mapping: imap <C-b> <Plug>(neosnippet_expand_or_jump)

![random-paste](https://user-images.githubusercontent.com/3723671/66718484-800fee00-edb2-11e9-84a9-88df2172b01c.gif)

**Comment by pappasam** [comment]
Python's v:completed_item: {'word': 'defd', 'menu': '[ns] def function(...): """..."""', 'user_data': '{"snippet_trigger": "defd", "snippet": "def ${1:#:n
ame}(${2}):\n\t\t\"\"\"${3:#:function documentation}\"\"\"\n\t\t${0:pass}"}', 'info': '', 'kind': '', 'abbr': ''}

**Comment by pappasam** [comment]
Yaml's v:completed_item: {'word': 'info:
        title: $1
        version: $2', 'menu': '[LC] ', 'user_data': '{"lspitem":{"label":"info","kind":10,"documentation":"","insertText":"info
:\n\ttitle: $1\n\tversion: $2","insertTextFormat":2,"textEdit":{"range":{"start":{"line":2,"character":0},"end":{"line":2,"char
acter":3}},"newText":"info:\n\ttitle: $1\n\tversion: $2"}},"snippet":"info:\n\ttitle: $1\n\tversion: $2"}', 'info': '', 'kind':
 'Property', 'abbr': 'info'}

**Comment by Shougo** [comment]
> Spuriously (not every time), the first "jump to next symbol" inserts the snippet again when using this key mapping: imap (neosnippet_expand_or_jump)

Because, LanguageClient-neovim's word is broken.
Snippet item is inserted directly.

2nd problem is not bug of neosnippet.

**Comment by Shougo** [comment]
And sorry.  I cannot test yaml-language-server.
So I don't want to test your problem.

**Comment by pappasam** [comment]
No worries! The python snippet problem will probably affect way more
people, so that’s the important one. I just listed the yaml issue for
completeness.

**Comment by Shougo** [comment]
https://github.com/Shougo/neosnippet.vim/issues/475#issuecomment-541431230

Fixed.  Please test the latest version.

**Comment by Shougo** [comment]
I have tested and installed yaml-languege-server.
But it does not work for me.

Oh,  it is bad.

**Comment by pappasam** [comment]
Haha, yeah, the latest version is broken. 0.4.1 is the most recent working version. https://github.com/redhat-developer/yaml-language-server/issues/192

And I tested your fixes; they work!

**Comment by Shougo** [comment]
Oh...

**Comment by pappasam** [comment]
If you want 0.4.1 of yaml-language-server to work, you'll need to configure it according to these docs: https://github.com/autozimu/LanguageClient-neovim/wiki/yaml-language-server

**Comment by pappasam** [comment]
Thanks for all the help! I'm guessing that based on your fixes, neosnippet will better-support more vscode-like language-servers going forward, which will be a great user experience improvement for lsp-supported snippets in neovim.

**Comment by Shougo** [comment]
OK.  I get it.  yaml-language-server works.

**Comment by Shougo** [comment]
`version` snippet is generated, but `info` is not generated.

**Comment by Shougo** [comment]
why??  I am confusing by the behavior.

**Comment by Shougo** [comment]
I don't fix the non-reproducible problems.  It is my policy.

**Comment by Shougo** [comment]
If you create the reproducible steps, I will test it later for yaml languege-server.
If not, my work is done.

**Comment by pappasam** [comment]
I'll open a new issue if I figure out how to describe the yaml-language-server issue clearly. I think this current issue is definitely resolved, thanks again for your help!
