### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by ashrasmun** [Shougo/neosnippet.vim#476]
Hello,

I've installed this plugin as described on the main page. I am using vanilla Vim 8.1 on Windows machine and not only does this plugin bombard me with errors inside Vim, but it also wants to use the HOME environment variable for some reason.

Am I just setting it up wrongly or it works only on unix-like systems?

Kind Regards

**Comment by Shougo** [comment]
I don't understand.
neosnippet should work in Windows environment.

You should create minimal vimrc like this.

https://github.com/Shougo/neosnippet.vim/issues/473

**Comment by Shougo** [comment]
> I am using vanilla Vim 8.1 on Windows machine and not only does this plugin bombard me with errors inside Vim, but it also wants to use the HOME environment variable for some reason.

You should upload the error messages.

**Comment by ashrasmun** [comment]
@Shougo I'm incredibly sorry, for bothering you. I solved my issue. My Vim distribution wasn't able to find Python and I had to define `pythonthreehome` as well as `pythonthreedll`. Everything works fine now :)

**Comment by Shougo** [comment]
OK.
