### ISSUE TITLE
Immediate expansion with trigger

### ISSUE THREAD

**Issue by al3xandru** [Shougo/neosnippet.vim#477]
I'm sorry for posting this as an issue but I could not find an answer.  I have a snippet which doesn't use any of the word/head/indent options; thus my expectation is that after typing the snippet and triggering its expansion that will happen.

Relevant conf options:

```
imap <C-e> <Plug>(neosnippet_expand_or_jump)
smap <C-e> <Plug>(neosnippet_expand_or_jump)
xmap <C-e> <Plug>(neosnippet_expand_target)
```

Snippet:

```
snippet zfn
abbr footnote
alias ^fn
    [^fn-${1:fn1}] ${3}

    [^fn-$1]: ${2:#:footnote text}
```

Given the above I expect that wherever I type `zfn` followed by <C-e> the snippet would expand.  What is incorrect in the above?  thank you

**Comment by Shougo** [comment]
You need to type `<C-e>`(`<Plug>(neosnippet_expand_or_jump)`).

**Comment by al3xandru** [comment]
@Shougo I apologize for my description above not being the most legible.

Yes, I do type `zfn` and then `C-e` and there is not expansion.  If there is a space before typing `zfn` then expansion works.  It looks like there is a default word bounder option.

**Comment by Shougo** [comment]
```
					 *g:neosnippet#expand_word_boundary*
g:neosnippet#expand_word_boundary
		If it is not 0, neosnippet will expand snippets by a word
		boundary.
		Note: It must be initialized before snippet loading.

		The default value is 0.
```

**Comment by al3xandru** [comment]
```
:echo g:neosnippet#expand_word_boundary
0
```

Are you saying that I need to change that to non-zero?

**Comment by Shougo** [comment]
The uploaded file is broken.

Please upload the reproduce instruction.
If not, I will ignore your report.

**Comment by Shougo** [comment]
`word` option default is `g:neosnippet#expand_word_boundary`.
So `g:neosnippet#expand_word_boundary` should work.

But you have not uploaded reproduce instruction.
We have not ESP skills.  I don't work for non reproduce issues.

**Comment by al3xandru** [comment]
@Shougo what do you mean by the uploaded file is broken?  The archive contains a short screen recording showing how typing a snippet and then trying to expand it while link to existing text does not expand.  I don't know how to report this in an easier way.


1.  Given the configuration above.
2.  Enter some text: "This is just a text"
3.  Continue now typing "zfn"
4.  Trigger expansion using `C-e`.

On my side nothing happens.  The only case when `C-e` actually triggers the expansion is when the string `zfn` is preceded by a space.

**Comment by Shougo** [comment]
OK.  It is reproduced and it is feature.
neosnippet searches textzfn snippet but it is not found.

You should know what is word boundary.
