### ISSUE TITLE
Unnamed register is destroyed 

### ISSUE THREAD

**Issue by tyru** [Shougo/neosnippet.vim#479]
## Problem

1. Delete text
1. Type `if<Tab>` to wrap the text with if-statement
1. Type `p` in if-block
1. `condition` is pasted

filetype is `go`. but maybe this problem does not depend on filetype.

![画面収録 2019-12-09 19 54 31](https://user-images.githubusercontent.com/48169/70431575-b327e280-1ac0-11ea-82e1-0c8477d2f354.gif)

## Expected

1. Delete text
1. Type `if<Tab>` to wrap the text with if-statement
1. Type `p` in if-block
1. **the deleted text is pasted**

**Comment by Shougo** [comment]
Sorry.  Unfortunately, this is Vim's select mode feature.

Select mode text breaks your unnamed register like visual mode.

**Comment by Shougo** [comment]
Note:  You have deleted selected text `condition`, so your unnamed register is broken.

**Comment by Shougo** [comment]
If you don't like the behavior, you need to request the feature in Vim issues instead.

**Comment by Shougo** [comment]
Note:

https://github.com/Shougo/neosnippet.vim/issues/471

The register restore feature is removed to fix the problem.
