### ISSUE TITLE
Regexp does not work

### ISSUE THREAD

**Issue by savchenko** [Shougo/neosnippet.vim#502]
Seems like the https://github.com/Shougo/neosnippet.vim/issues/190 is back:

```snip
snippet	nn
abbr	name: Task snippet
regexp	\-\ name
options	indent
	name: ${1:task}
	${2:#:module}:
				${3:#:parameter}: ${4}
			${5:#:when:}
```

With `listchars`:

![image](https://user-images.githubusercontent.com/300146/130200120-a6510531-d265-42dd-ab3c-f79aec609e32.png)

The snippet does not expand no matter where I type `- name`. I can call it only via `nn`. Have tried numerous variations of the same regexp (e.g. `\s` instead of `\ `) but all in vain.

Had to use hard <kbd>Tab</kbd> as otherwise all lines were squashed to the beginning of the line.

**Comment by Shougo** [comment]
Please read the documentation.
It must be quoted like this:

```
regexp	'- name'
```

And the regexp feature is not for auto expand.  It is used for manual expand.
The (pattern matched) auto expand is not implemented in neosnippet.
