### ISSUE TITLE
Avoid triggering `InsertLeave` 

### ISSUE THREAD

**Issue by savchenko** [Shougo/neosnippet.vim#503]
I have the following mapping to avoid "jumping" cursor when exiting Insert mode:
```vim
autocmd InsertLeave * :normal! `^
```
Works great, however this leads to incorrect manual expansion in Neosnippet.

Example snippet:
```snip
snippet vv
abbr    Jinja: variable
options indent
        {{ ${1: variable } }}
```

if `vv` is the last word in line, everything works fine. 
However if there is anything after it, the expansion will result in `v{{ variable }}`

Would it be possible to use <kbd>C-c</kbd> inside of the plugin to avoid triggering `InsertLeave`? 
Are there any other workarounds you might think of?

**P.S.** Neosnippet is pretty damn handy. Kudos!

**Comment by Shougo** [comment]
Sorry.  I cannot fix the problem.
`<ESC>:` is used to implement the snippet plugin.
So `InsertLeave` is triggered.

**Comment by Shougo** [comment]
I have replaced `<Esc>` to `<C-c>`.  It seems work.

**Comment by savchenko** [comment]
> I have replaced `<Esc>` to `<C-c>`. It seems work.

It does work! Thank you.
