### ISSUE TITLE
Feature Request: snippet ファイルでプレースホルダのミラー($0)をエスケープする方法が欲しい

### ISSUE THREAD

**Issue by rhysd** [Shougo/neosnippet.vim#99]
Ruby にて

```
snippet		main
abbr		if __FILE__ == $0
	#
	# main
	#
	if __FILE__ == $0
		${1}
	end # if __FILE__ = $0
```

というスニペットを設定したのですが，$0 が synchronized placeholder として認識されてしまいます．
\` や ${} の括弧内の文字列はバックスラッシュでエスケープできるようなのですが，`$number` をエスケープする方法をお願いできませんでしょうか．

**Comment by Shougo** [comment]
`$0` は `\$0` のようにエスケープできることを確認したのでクローズします。

**Comment by rhysd** [comment]
ありがとうございました．試してみます．
